#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"

class CK2CustomScenario < ParadoxModBuilder
  def titles_to_clean_up
    @titles_to_clean_up ||= Set[*begin
      @game.glob("history/titles/[ek]_*.txt").map{|path|
        path.basename(".txt").to_s
      } - ["k_papal_state", "k_orthodox"]
    end]
  end

  def no_kingdoms_empires_and_nomads!
    @game.glob("history/titles/*.txt").each do |path|
      title = path.basename(".txt").to_s
      if titles_to_clean_up.include?(title)
        patch_mod_file!(path) do |node|
          node.each do |date, attrs|
            attrs.delete "holder"
            attrs.delete "historical_nomad"
            attrs.delete "liege"
          end
          node.delete_if{|k,v| v.empty?}
        end
      else
        patch_mod_file!(path) do |node|
          node.each do |date, attrs|
            attrs.delete "historical_nomad"
            attrs.delete_if do |k,v|
              k == "liege" and titles_to_clean_up.include?(v)
            end
          end
          node.delete_if{|k,v| v.empty?}
        end
      end
    end
  end

  def build_mod_files!
    no_kingdoms_empires_and_nomads!
    # Do all the fun things
  end
end

mb = CK2CustomScenario.new(
  ParadoxGame.new(
    "source/ck2_2.4.3",
  ),
  "output/custom_scenario"
)
mb.build!
