#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
require_relative "mods/no_localized_landed_titles"

class NoLocalizedTitlesModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/ck2_2.4.3",
      ),
      "output/no_localized_landed_titles",
    )
  end
  def build_mod_files!
    apply_modifications! NoLocalizedTitlesGameModification
    create_mod_descriptor!(
      name: "No Localized Landed Titles",
      path: "mod/no_localized_landed_titles",
      picture: "no_localized_landed_titles.png",
    )
  end
end

NoLocalizedTitlesModBuilder.new.build!
