#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"

class NoDynasticNamesGameModification < ParadoxGameModification
 def no_dynastic_country_names!
    patch_mod_files!("common/cultures/*.txt") do |node|
      node.each do |group_name, group|
        group.each do |culture_name, culture|
          next if culture_name == "graphical_culture"
          next if culture_name == "second_graphical_culture"
          next if culture_name == "graphical_cultures"
          culture.delete("dynasty_title_names")
        end
      end
    end
  end

  def apply!
    no_dynastic_country_names!
  end
end

class NoDynasticNamesModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/ck2_2.4.3",
      ),
      "output/no_dynastic_names"
    )
  end

  def build_mod_files!
    apply_modifications! NoDynasticNamesGameModification
    create_mod_descriptor!(
      name: "No Dynastic Names",
      path: "mod/no_dynastic_names",
      picture: "no_dynastic_names.png",
    )
  end
end

if __FILE__ == $0
  NoDynasticNamesModBuilder.new.build!
end
