#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
Pathname(__dir__).glob("mods/*.rb").each{|rb| require_relative rb}

class CK2PlusTweaksGameModification < CK2TweaksGameModification
  def seduce_any_religion!
    patch_mod_file!("decisions/way_of_life_decisions.txt") do |node|
      allow = node["targeted_decisions"]["seduce_decision"]["allow"]
      allow_orig = allow.dup
      allow.delete!{|prop|
        prop == Property["religion_group", "FROM"]
      }
      raise "Can't find condition" if allow == allow_orig
    end
  end

  def nerf_holy_wars_cb!
    patch_mod_file!("common/cb_types/00_cb_types.txt") do |node|
      # Does it work?
      node["holy_war"]["check_de_jure_tier"] = "COUNT"
    end
  end

  def revert_bad_ck2plus_changes!
    override_defines_lua!("revert_bad_ck2plus_changes",
      "NCharacter.TREASURY_CHANCE_TO_DISAPPEAR_STANDARD" => 0,
      "NCharacter.TREASURY_CHANCE_TO_DISAPPEAR_NO_HEIR" => 0,
      "NEconomy.PATRICIAN_CITY_TAX_MULT" => 0.50,
      "NEconomy.OVER_MAX_DEMESNE_TAX_PENALTY" => 0.20,
      "NEconomy.TAX_TO_LOOT_MULTIPLIER" => 1.0,
      "NEconomy.FORT_LOOT_DEFENCE_MULTIPLIER" => 4.0,
      "NEconomy.LOOTABLE_GOLD_REGROWTH" => 0.015,
      "NEconomy.LOOT_PRESTIGE_MULT" => 1,
      "NEconomy.LOOT_EVERY_X_DAYS" => 4,
    )
    # Forunately they removed naval attrition already
  end

  def terrain_bonus(icon, atk, defs)
    PropertyList[
      "icon", icon,
      "archers_offensive", atk,
      "camel_cavalry_offensive", atk,
      "free_levies_in_offensive", atk,
      "heavy_infantry_offensive", atk,
      "horse_archers_offensive", atk,
      "knights_offensive", atk,
      "light_cavalry_offensive", atk,
      "light_infantry_offensive", atk,
      "nomad_horse_offensive", atk,
      "pikemen_offensive", atk,
      "war_elephants_offensive", atk,
      "archers_defensive", defs,
      "camel_cavalry_defensive", defs,
      "free_levies_in_defensive", defs,
      "heavy_infantry_defensive", defs,
      "horse_archers_defensive", defs,
      "knights_defensive", defs,
      "light_cavalry_defensive", defs,
      "light_infantry_defensive", defs,
      "nomad_horse_defensive", defs,
      "pikemen_defensive", defs,
      "war_elephants_defensive", defs,
    ].select!{|prop| prop.val != 0}
  end

  def increase_terrain_bonuses!
    # CK2+ makes terrain bonuses even weaker
    patch_mod_file!("common/static_modifiers.txt") do |node|
      node["river_crossing"] = terrain_bonus(2, -0.3, 0.0)
      node["major_river_crossing"] = terrain_bonus(2, -0.5, 0.0)
      node["strait_river_crossing"] = terrain_bonus(3, -0.5, 0.0)
      node["amphibious_landing"] = terrain_bonus(4, -0.5, 0.0)
      node["defenderbonus_mountain"] = terrain_bonus(1, 0.0, 0.8)
      node["defenderbonus_hills"] = terrain_bonus(1, 0.0, 0.6)
      node["defenderbonus_forest"] = terrain_bonus(1, 0.0, 0.4)
      node["defenderbonus_jungle"] = terrain_bonus(1, 0.0, 0.4)
    end
  end

  def remove_easy_mode_laws!
    patch_mod_file!("common/laws/crown_laws.txt") do |node|
      # Inheritance always possible
      laws = node["de_jure_laws"]
      laws["out_of_realm_inheritance_law_0"]["effect"]["set_protected_inheritance"] = false
      laws["out_of_realm_inheritance_law_1"]["effect"]["set_protected_inheritance"] = false
    end

    patch_mod_file!("common/laws/demesne_laws.txt") do |node|
      node["laws"]["revoke_title_law_2"]["effect"]["set_allow_free_infidel_revokation"] = false
    end

    # Reorder them in more sensible way:
    # * council power
    # then:
    # * execution
    # * banishment
    # * imprison
    # * revoke
    # * war
    # * grant
    patch_mod_file!("common/laws/ze_council_power_laws.txt") do |node|
      laws = node["laws"]

      laws["imprison_voting_power_1"]["allow"].delete!(Property["has_law", "war_voting_power_1"])
      laws["revoke_title_voting_power_1"]["allow"].delete!(Property["has_law", "war_voting_power_1"])
      laws["grant_title_voting_power_1"]["allow"].delete!(Property["has_law", "war_voting_power_1"])
      laws["banish_voting_power_1"]["allow"].delete!(Property["has_law", "war_voting_power_1"])
      laws["execution_voting_power_1"]["allow"].delete!(Property["has_law", "war_voting_power_1"])

      laws["war_voting_power_0"]["allow"].delete!(Property["has_law", "banish_voting_power_0"])
      laws["war_voting_power_0"]["allow"].delete!(Property["has_law", "revoke_title_voting_power_0"])
      laws["war_voting_power_0"]["allow"].delete!(Property["has_law", "grant_title_voting_power_0"])
      laws["war_voting_power_0"]["allow"].delete!(Property["has_law", "imprison_voting_power_0"])
      laws["war_voting_power_0"]["allow"].delete!(Property["has_law", "execution_voting_power_0"])
    end
  end

  def apply!
    extra_cb_de_jure_duchy_conquest!
    extra_cb_abolish_title!
    allow_intermarriage!
    fix_gavelkind!
    reduce_wrong_gov_type_penalties!
    seduce_any_religion!
    increase_trade_post_limit!
    allow_everyone_river_access!
    # dont_call_duke_kings_ever! # culture file crashes
    allow_more_commanders!
    fix_hostile_supply!
    divine_blood_full_fertility!
    more_battle_captives!
    # fix_regency! # supposedly fixed in base game?
    more_zoom!
    no_random_coas!
    nerf_holy_wars_cb!
    create_minimal_hunie_trait!
    allow_heir_designation!
    allow_joining_all_wars!
    # adventurers_cap! # not sure if still needed
    # much_less_attriton! # not sure if still needed
    # remove_siege_defense_bonus!
    makes_title_creation_expensive!
    # open_societies! # probably still needed

    # CK2+ specific
    revert_bad_ck2plus_changes!

    # Megacampaign specific
    increase_terrain_bonuses!
    remove_easy_mode_laws!
  end
end

class CK2TweaksModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/ck2_2.8.1",
        "source/CK2Plus_v4071/CK2Plus.mod",
      ),
      "output/ck2plus_tweaks",
    )
  end
  def build_mod_files!
    apply_modifications! CK2PlusTweaksGameModification,
                         RulerDesignerResetGameModification
    create_mod_descriptor!(
      name: "CK2+ Tweaks",
      path: "mod/ck2plus_tweaks",
    )
  end
end

CK2TweaksModBuilder.new.build!
