#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
Pathname(__dir__).glob("mods/*.rb").each{|rb| require_relative rb}

class CK2TweaksModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/ck2_2.6.1",
      ),
      "output/ck2tweaks",
    )
  end
  def build_mod_files!
    apply_modifications! CK2TweaksGameModification,
                         UITweaksGameModification,
                         BecomeRepublicGameModification,
                         VassalTransferGameModification,
                         DynasticDecisionsGameModification,
                         RulerDesignerResetGameModification,
                         SuezCanalGameModification,
                         FactionResistanceGameModification
    create_mod_descriptor!(
      name: "CK2 Tweaks",
      path: "mod/ck2tweaks",
    )
  end
end

CK2TweaksModBuilder.new.build!
