#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
Pathname(__dir__).glob("mods/*.rb").each { |rb| require_relative rb }

class ModernTimesPlusModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/ck2_3.0.0",
      ),
      "output/modern_times_plus",
    )
  end

  # Should always be same as in ModernTimesModBuilder
  def apply_modern_times!
    # Hotfix 2.8
    patch_file!("common/landed_titles/landed_titles.txt") do |content|
      content.sub("b_qobadhiyan {}", " b_qobadhiyan = {}")
    end
    apply_modifications! SuezCanalGameModification,
                         NoDynasticNamesGameModification,
                         ProtestantismGameModification,
                         BelarusianCultureGameModification,
                         UkrainianCultureGameModification,
                         AmericanCultureGameModification,
                         CanadianCultureGameModification,
                         BrazilianCultureGameModification,
                         ModernTimesGameModification
  end

  def apply_ck2tweaks!
    apply_modifications! CK2TweaksGameModification,
                         UITweaksGameModification,
                         BecomeRepublicGameModification,
                         NoLocalizedRanksGameModification,
                         NoLocalizedTitlesGameModification,
                         VassalTransferGameModification,
                         DynasticDecisionsGameModification,
                         RulerDesignerResetGameModification,
                         FactionResistanceGameModification
  end

  def build_mod_files!
    apply_modern_times!
    apply_ck2tweaks!
    create_mod_descriptor!(
      name: "Modern Times Plus",
      path: "mod/modern_times_plus",
    )
  end
end

ModernTimesPlusModBuilder.new.build!
