#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
require_relative "mods/no_localized_ranks"

class NoLocalizedRanksModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/ck2_2.5.1",
      ),
      "output/no_localized_ranks",
    )
  end
  def build_mod_files!
    apply_modifications! NoLocalizedRanksGameModification
    create_mod_descriptor!(
      name: "No Localized Ranks",
      path: "mod/no_localized_ranks",
      picture: "no_localized_ranks.png",
    )
  end
end

NoLocalizedRanksModBuilder.new.build!
