#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
require_relative "mods/no_dynastic_names"

class NoDynasticNamesModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/ck2_2.4.3",
      ),
      "output/no_dynastic_names"
    )
  end
  def build_mod_files!
    apply_modifications! NoDynasticNamesGameModification
    create_mod_descriptor!(
      name: "No Dynastic Names",
      path: "mod/no_dynastic_names",
      picture: "no_dynastic_names.png",
    )
  end
end

NoDynasticNamesModBuilder.new.build!
