#!/usr/bin/env ruby

require_relative "save_game"
require_relative "localization"

unless ARGV.size == 1 or ARGV.size == 2
  STDERR.puts "Usage: #{$0} <file.eu4> [<tag>]"
  exit 1
end

save_path = ARGV[0]
target_tag = ARGV[1] ? ARGV[1].to_sym : nil
ae = []

SaveGame.new(save_path)[:countries].each do |country_data|
  source = country_data.key
  country_data[:active_relations].each do |relation|
    target = relation.key
    next unless target == target_tag if target_tag
    relation.content.each do |node|
      next unless node.key == :opinion
      next unless node[:modifier].content == "aggressive_expansion"
      ae << ["#{Localization[source]} (#{source} vs #{target})",  node[:current_opinion].content]
    end
  end
end

ae.sort_by{|k,v| [v, k]}.each{|k,v| puts [k,v].join("\t")}
