#!/usr/bin/env ruby

require "set"
require "pathname"
require "pp"

class Pathname
  alias_method :to_str, :to_s
end

class FindRedundantFiles
  def initialize(dir1, dir2)
    @dir1 = Pathname(dir1)
    @dir2 = Pathname(dir2)
  end

  def test_if_redundant!(path)
    puts path if `diff -qw '#{@dir1+path}' '#{@dir2+path}'`.empty?
  end

  def files_in(path)
    Set[
      *path.find.select(&:file?).map do |f|
        Pathname(f.relative_path_from(path).to_s.downcase)
      end
    ]
  end

  def call
    files1 = files_in(@dir1)
    files2 = files_in(@dir2)

    (files1 & files2).each do |path|
      test_if_redundant!(path)
    end
  end
end

unless ARGV.size == 2
  STDERR.puts "Usage: #{$0} dir1 dir2"
  exit 1
end

FindRedundantFiles.new(*ARGV).call
