#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class CulturesAnalysis < CK2GameAndSaveAnalysis
  def call
    @by_realm = {}

    @data["provinces"].each do |id, province|
      province_title = province_id_to_title[id]
      next unless province_title
      realm = top_realm_by_title(province_title)
      culture = province["culture"] || "empty"
      @by_realm[realm] ||= Hash.new(0)
      @by_realm[realm][culture] += 1
    end

    @by_realm.each do |realm, cultures|
      cultures.sort_by{|c,s| [-s, c]}.each do |culture, size|
        puts "#{realm}\t#{size}\t#{culture}"
      end
    end
  end
end

CulturesAnalysis.new(*ARGV).call
