#!/usr/bin/env ruby

require_relative "../lib/paradox"
require_relative "ck2_analyses"

class EmptyHoldingsAnalysis
  include Ck2Analyses
  def initialize(path)
    @path = path
    @data = ParadoxModFile.new(path: @path).parse!
  end

  # Not sure how it deals with nomad counties
  def run!
    realms = Hash.new(0)
    @data["provinces"].each do |id, province|
      next if province == []
      holding_names = valid_titles & province.keys
      next if holding_names.empty?
      primary =  province["primary_settlement"]
      built = holding_names.size
      max = province["max_settlements"] || built
      if primary == "---"
        realm = "---"
      else
        realm = top_realm_by_title(primary)
      end
      free = max - built
      realms[realm] += free if free > 0
    end
    realms.sort_by(&:last).reverse.each do |realm, free|
      puts "#{realm_name(realm)} #{free}"
    end
  end
end

unless ARGV.size == 1
  STDERR.puts "Usage: #{$0} <save.ck2> # non-compressed save only"
  exit 1
end

EmptyHoldingsAnalysis.new(ARGV[0]).run!
