#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class ListSecretBelieversAnalysis < CK2GameAndSaveAnalysis
  def run!
    load_characters!

    Character.each do |character_id, c|
      secret_religion = c.node["secret_religion"]
      next unless secret_religion
      titles = c.top_tier_titles.join("/")
      of_title = titles.empty? ? "(landless)" : "of #{titles}"
      puts "#{c.full_name} #{of_title} #{c.alive? ? 'is' : 'was'} secretly #{localization(secret_religion)} publicly #{localization(c.religion)}"
    end
  end
end

ListSecretBelieversAnalysis.new(*ARGV).run!
