#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class ListArtifactsAnalysis < CK2GameAndSaveAnalysis
  def artifact_types
    @artifact_types ||= begin
      map = {}
      glob("common/artifacts/*.txt").each do |path|
        parse(path).each do |id, artifact|
          next if id == "slots"
          name = localization(id)
          if id =~ /\Amagnum_opus_.*_(\d+)\z/
            name += " #{$1}"
          end
          map[id] = {
            name: name,
            quality: artifact["quality"] || "?",
          }
        end
      end
      map
    end
  end

  def artifact_owners
    @artifact_owners ||= begin
      map = {}
      @data["artifacts"].each do |artifact_id, artifact|
        # No idea wtf this is about
        next if artifact == "none"
        name = artifact["type"]
        owner_id = artifact["owner"]
        raise "Artifact with no name: #{artifact}" unless name
        raise "Artifact with no owner: #{artifact}" unless owner_id
        item = artifact_types[name]
        raise "No such item: #{name}" unless item
        quality = item[:quality]
        # Don't bother with crap
        # Strange chest has no quality
        map[owner_id] ||= []
        map[owner_id] << name
      end
      map
    end
  end

  def run!
    load_characters!

    report = []

    artifact_owners.each do |owner_id, items|
      owner = Character[owner_id]
      owner_name = "#{owner.full_name} of #{owner.top_tier_titles.join("/")}"

      capital = owner.titles.map(&:id).find{|t| t =~ /\A[cb]_/ and title_paths[t]}

      if capital
        location_path = title_paths[capital].reverse.join("/")
      elsif !owner.titles.empty?
        # has title but no capital, like landless pope or independent nomad clan
        location_path = "?"
      elsif
        host = Character[owner.node["host"]]
        host_capital = host.titles.map(&:id).find{|t| t =~ /\A[cb]_/ and title_paths[t]}
        if host_capital
          location_path = title_paths[host_capital].reverse.join("/")
        else
          location_path = "?"
        end
      end

      items.each do |id|
        item = artifact_types[id]
        report << "#{location_path} - #{owner_name} - #{item[:name]} [#{item[:quality]}]"
      end
    end

    puts report.sort
  end
end

ListArtifactsAnalysis.new(*ARGV).run!
