#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class ListSecretBelieversAnalysis < CK2GameAndSaveAnalysis
  def secret_traits
    @secret_traits ||= begin
      map = {}
      traits.each do |i, name|
        map[i] = name if name =~ /\Asecretly_/
      end
      map
    end
  end

  def run!
    load_characters!

    Character.each do |character_id, c|
      secret_ids = (c.trait_ids & secret_traits.keys)
      next if secret_ids.empty?
      # I don't think it's likely you'll be multiple
      secret_name = secret_ids.map{|t| secret_traits[t].sub(/\Asecretly_/, "")}.join("/")
      titles = c.top_tier_titles.join("/")
      of_title = titles.empty? ? "(landless)" : "of #{titles}"
      puts "#{c.full_name} #{of_title} #{c.alive? ? 'is' : 'was'} secretly #{secret_name}"
    end
  end
end

ListSecretBelieversAnalysis.new(*ARGV).run!
