#!/usr/bin/env ruby

require_relative "ck2_analyses"

class ProvinceTechAnalysis < CK2SaveAnalysis
  def run!
    province_techs.sort_by{|info| [-info[:tech], info[:name]] }.each do |info|
      province_realms = realms(info[:id]).map{|realm| realm_name(realm)}
      puts [info[:tech], info[:name], province_realms.join("\t"), info[:id]].join("\t")
    end
  end
end

ProvinceTechAnalysis.new(*ARGV).run!
