#!/usr/bin/env ruby

require_relative "ck2_analyses"

class ProvinceReligionsAnalysis < CK2SaveAnalysis
  def run!
    religions = Hash.new(0)
    @data["provinces"].each do |id, province|
      religion = province["religion"]
      religions[religion] += 1 if religion
    end

    religions.sort_by{|c,n| [-n,c]}.each do |religion, count|
      puts "#{count} #{religion}"
    end
  end
end

ProvinceReligionsAnalysis.new(*ARGV).run!
