#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class ProvinceCulturesAnalysis < CK2SaveAnalysis
  def call
    cultures = Hash.new(0)
    @data["provinces"].each do |id, province|
      culture = province["culture"]
      cultures[culture] += 1 if culture
    end

    cultures.sort_by{|c,n| [-n,c]}.each do |culture, count|
      puts "#{count} #{culture}"
    end
  end
end

ProvinceCulturesAnalysis.new(*ARGV).call
