#!/usr/bin/env ruby

require_relative "../lib/paradox"
require_relative "ck2_analyses"

class ReligionsAnalysis < ParadoxGame
  include Ck2Analyses
  def initialize(save_game, *roots)
    super(*roots)
    @path = save_game
    @data = ParadoxModFile.new(path: @path).parse!
  end

  def run!
    @by_realm = {}

    @data["provinces"].each do |id, province|
      province_title = province_id_to_title[id]
      next unless province_title
      realm = top_realm_by_title(province_title)
      religion = province["religion"] || "empty"
      @by_realm[realm] ||= Hash.new(0)
      @by_realm[realm][religion] += 1
    end

    @by_realm.each do |realm, religions|
      religions.sort_by{|c,s| [-s, c]}.each do |religion, size|
        puts "#{realm}\t#{size}\t#{religion}"
      end
    end
  end
end

unless ARGV.size >= 2
  STDERR.puts "Usage: #{$0} <save.ck2> <root> [<mod1> <mod2> ... ] # non-compressed save only"
  exit 1
end

ReligionsAnalysis.new(*ARGV).run!
