#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class ReligionsAnalysis < CK2GameAndSaveAnalysis
  def call
    @by_realm = {}

    @data["provinces"].each do |id, province|
      province_title = province_id_to_title[id]
      next unless province_title
      realm = top_realm_by_title(province_title)
      religion = province["religion"] || "empty"
      @by_realm[realm] ||= Hash.new(0)
      @by_realm[realm][religion] += 1
    end

    @by_realm.each do |realm, religions|
      religions.sort_by{|c,s| [-s, c]}.each do |religion, size|
        puts "#{realm}\t#{size}\t#{religion}"
      end
    end
  end
end

ReligionsAnalysis.new(*ARGV).call
