#!/usr/bin/env ruby

require_relative "ck2_analyses"

class TraitsTranslationTableAnalysis < CK2GameAnalysis
  def run!
    traits.each do |i, name|
      puts "#{i} #{localization(name)}"
    end
  end
end

TraitsTranslationTableAnalysis.new(*ARGV).run!
