#!/usr/bin/env ruby

require_relative "../lib/paradox"

class TraitsTranslationTableAnalysis < ParadoxGame
  def traits
    @traits ||= begin
      map = {}
      glob("common/traits/*").sort.each do |path|
        parse(path).each do |name, trait|
          map[map.size+1] = name
        end
      end
      map
    end
  end

  def run!
    traits.each do |i, name|
      puts "#{i} #{localization(name)}"
    end
  end
end

unless ARGV.size >= 1
  STDERR.puts "Usage: #{$0} <root> [<mod1> <mod2> ... ]"
  exit 1
end

TraitsTranslationTableAnalysis.new(*ARGV).run!
