#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class TraitsTranslationTableAnalysis < CK2GameAnalysis
  def call
    traits.each do |i, name|
      puts "#{i} #{localization(name)}"
    end
  end
end

TraitsTranslationTableAnalysis.new(*ARGV).call
