#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class TraitsStatisticsAnalysis < CK2GameAndSaveAnalysis
  def run!
    alive = Hash.new(0)
    dead  = Hash.new(0)
    total = Hash.new(0)
    @data["character"].each do |character_id, character|
      character_traits = character["traits"] or next
      character_alive = !character["d_d"]
      character_traits.each do |trait_id|
        if character_alive
          alive[trait_id] += 1
        else
          dead[trait_id] += 1
        end
        total[trait_id] += 1
      end
    end

    (1...total.keys.max).each do |id|
      trait_name = traits[id]
      loc = trait_name ? traits[id] : id
      puts "#{id} #{loc} #{alive[id]} #{dead[id]} #{alive[id]+dead[id]}"
    end
  end
end

TraitsStatisticsAnalysis.new(*ARGV).run!
