#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class TribalDevelopmentAnalysis < CK2SaveAnalysis
  def realm(id)
    province = @data["provinces"][id]
    province_titles = valid_titles & province.keys
    top_realms = province_titles.map do |title|
      top_realm_by_title(title)
    end.uniq

    top_realms.sort.join(" / ")
  end

  def run!
    realms = {}
    @data["provinces"].each do |id, province|
      next if province == []
      holding_names = valid_titles & province.keys
      holding_names.each do |name|
        realm = top_realm_by_title(name)
        holding = province[name]
        development_level = holding["type"]

        if holding["type"] == "tribal"
          (1..4).each do |i|
            if holding["tb_hillfort_#{i}"]
              development_level = "tribal (hillfort #{i})"
            end
          end
        end
        realms[realm] ||= Hash.new(0)
        realms[realm][development_level] += 1
      end
    end
    realms.sort_by{|name, data| [-data.values.inject(&:+), name]}.each do |name, data|
      puts "#{realm_name(name)} #{data.inspect}"
    end
  end
end

TribalDevelopmentAnalysis.new(*ARGV).run!
