#!/usr/bin/env ruby

require_relative "../ck2/ck2_analyses"

class Character
  def print_dynasty_tree(prefix="")
    puts "#{prefix}#{name} (#{culture}; #{religion})"
    if father
      father.print_dynasty_tree("#{' ' * prefix.size}F: ")
    end
    if mother
      mother.print_dynasty_tree("#{' ' * prefix.size}M: ")
    end
  end

  def print_vassal_tree(prefix="")
    puts "#{prefix}#{full_name} of #{top_tier_titles.join("/")} (#{culture}; #{religion})"
    vassals.sort_by{|v| -v.tier}.each do |v|
      v.print_vassal_tree("#{' ' * prefix.size}* ")
    end
  end
end

class VassalCulturesAnalysis < CK2SaveAnalysis
  def call
    load_characters!
    player.print_vassal_tree
  end
end

VassalCulturesAnalysis.new(*ARGV).call
