#!/usr/bin/env ruby

require "./save_game"
require "./localization"

def each_diplomatic_relation(country_data)
  country_data.each do |node|
    key, = node.keys
    val, = node.values
    val.each do |entry|
      if entry[:active_relations]
        entry[:active_relations].each do |node2|
          key2, = node2.keys
          val2, = node2.values
          yield(key, key2, val2)
        end
      end
    end
  end
end

if ARGV.size != 2
  STDERR.puts "Usage: #{$0} <file.sav> <tag>"
  exit 1
end

save_path = ARGV[0]
tag = ARGV[1].to_sym
ae = []

SaveGame.new(save_path).parse do |x|
  if x[:countries]
    each_diplomatic_relation(x[:countries]) do |source, target, rel|
      next unless target == tag
      rel.each do |r|
        next unless r[:opinion]
        r = r[:opinion].inject(&:merge)
        next unless r[:modifier] == "aggressive_expansion"
        ae << ["#{localization[source.to_s]} (#{source})", r[:current_opinion]]
      end
    end
  end
end

ae.sort_by{|k,v| [v, k]}.each{|k,v| puts [k,v].join("\t")}
