source "https://rubygems.org"

# csv is a bundled gem from ruby 3.4 on, so it has to be declared
gem "csv"
gem "memoist"
gem "minitest"
gem "paint"
gem "pry"
gem "rake"
gem "rgl"
gem "rmagick"
gem "rspec"
gem "rubyzip"
gem "simplecov", "~> 1.0"
gem "simplex"
