#!/usr/bin/env ruby

require "./save_game"
require "./localization"

unless ARGV.size == 1
  STDERR.puts "Usage: #{$0} <file.sav>"
  exit 1
end

save_path = ARGV[0]

SaveGame.new(save_path)[:countries].content.each do |country_data|
  country_name = Localization[country_data.key]
  tech_group = country_data[:technology_group]
  tech_group &&= tech_group.content
  puts [country_name, tech_group || "-"].join("\t")
end
