CanadaInvasionEvents = PropertyList[
  "namespace", "CANADA",
  "province_event", PropertyList[
    "id", "CANADA.1",
    "desc", "EVTDESC_CANADA_001",
    "picture", "GFX_evt_aztec_explorers",
    "border", "GFX_event_normal_frame_war",
    "trigger", PropertyList[
      "has_dlc", "Sunset Invasion",
      "year", 2000,
      "NOT", PropertyList["year", 2100],
      "NOT", PropertyList["has_global_flag", "canadian_explorers"],
      "OR", PropertyList[
        "province_id", 9,
        "province_id", 31,
        "province_id", 37,
        "province_id", 56,
        "province_id", 267,
        "province_id", 268,
        "province_id", 303,
        "province_id", 393,
        "province_id", 396,
      ],
    ],
    "immediate", PropertyList[
      "set_global_flag", "canadian_explorers",
      "set_province_flag", "canadian_explorers",
      "activate_title", PropertyList[
        "title", "e_canada",
        "status", true,
      ],
      "k_papal_state", PropertyList["holder_scope", PropertyList[
                                      "create_random_soldier", PropertyList[
                                        "dynasty", 1035000,
                                        "random_traits", true,
                                        "culture", "canadian",
                                        "religion", "protestant",
                                      ],
                                      "new_character", PropertyList[
                                        "e_canada", PropertyList["grant_title", "PREV"],
                                        "set_government_type", "feudal_government",
                                        "set_defacto_liege", "THIS",
                                        "narrative_event", PropertyList[
                                          "id", "CANADA.2",
                                          "days", 7,
                                        ],
                                      ],
                                    ]],
    ],
    "mean_time_to_happen", PropertyList[
      "months", 7200,
      "modifier", PropertyList[
        "factor", 0.5,
        "year", 2050,
      ],
    ],
    "option", PropertyList["name", "EVTOPTA_CANADA_001"],
  ],
  "narrative_event", PropertyList[
    "id", "CANADA.2",
    "title", "EVTNAME_CANADA_002",
    "desc", "EVTDESC_CANADA_002",
    "major", true,
    "picture", "GFX_evt_aztec_explorers",
    "border", "GFX_event_narrative_frame_war",
    "is_triggered_only", true,
    "major_trigger", PropertyList["FROM", PropertyList["owner", PropertyList["NOT", PropertyList["character", "PREVPREV"]]]],
    "immediate", PropertyList["e_canada", PropertyList["holder_scope", PropertyList["character_event", PropertyList["id", "CM.10018"]]]],
    "option", PropertyList["name", "EVTOPTA_CANADA_002"],
  ],
  "province_event", PropertyList[
    "id", "CANADA.3",
    "desc", "EVTDESC_CANADA_003",
    "picture", "GFX_evt_battle_mesoamerican",
    "border", "GFX_event_normal_frame_war",
    "trigger", PropertyList[
      "year", 2000,
      "NOT", PropertyList["has_global_flag", "canadian_arrival"],
      "had_province_flag", PropertyList[
        "flag", "canadian_explorers",
        "days", 730,
      ],
    ],
    "immediate", PropertyList[
      "set_global_flag", "canadian_arrival",
      "e_canada", PropertyList["holder_scope", PropertyList["narrative_event", PropertyList["id", "CANADA.4"]]],
    ],
    "mean_time_to_happen", PropertyList["months", 6],
    "option", PropertyList["name", "EVTOPTA_CANADA_003"],
  ],
  "narrative_event", PropertyList[
    "id", "CANADA.4",
    "title", "EVTNAME_CANADA_004",
    "desc", "EVTDESC_CANADA_004",
    "major", true,
    "hide_new", true,
    "picture", "GFX_evt_battle_mesoamerican",
    "border", "GFX_event_narrative_frame_war",
    "is_triggered_only", true,
    "major_trigger", PropertyList["FROM", PropertyList["owner", PropertyList["NOT", PropertyList["character", "PREVPREV"]]]],
    "immediate", PropertyList[
      "any_playable_ruler", PropertyList[
        "limit", PropertyList[
          "ai", false,
          "capital_scope", PropertyList["NOT", PropertyList["region", "world_india"]],
        ],
        "character_event", PropertyList["id", "CM.10020"],
      ],
      "wealth", 10000,
      "FROM", PropertyList["kingdom", PropertyList["ROOT", PropertyList["war", PropertyList[
                                                                          "casus_belli", "tribal_invasion",
                                                                          "target", "PREVPREV",
                                                                          "thirdparty_title", "PREV",
                                                                        ]]]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 31,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 24,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 23,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 18,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 28,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 29,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
      ],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
      ],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
      ],
      "if", PropertyList[
        "limit", PropertyList["FROM", PropertyList["OR", PropertyList[
                                                     "province_id", 1,
                                                     "province_id", 9,
                                                     "province_id", 35,
                                                     "province_id", 31,
                                                   ]]],
        "FROM", PropertyList["sea_zone", PropertyList["ROOT", PropertyList["spawn_unit", PropertyList[
                                                                             "province", "PREV",
                                                                             "home", "FROM",
                                                                             "owner", "ROOT",
                                                                             "earmark", "canadian_invasion_fleet",
                                                                             "troops", PropertyList["galleys", [1000, 1000]],
                                                                           ]]]],
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 20,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 25,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 26,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 28,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 17,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", true,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", true,
        "age", 17,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", true,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", true,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", true,
        "age", 20,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", true,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", true,
        "age", 16,
      ],
    ],
    "option", PropertyList["name", "EVTOPTA_CANADA_004"],
  ],
  "province_event", PropertyList[
    "id", "CANADA.5",
    "desc", "EVTDESC_CANADA_005",
    "picture", "GFX_evt_aztec_arrival",
    "border", "GFX_event_normal_frame_war",
    "trigger", PropertyList[
      "year", 2000,
      "has_global_flag", "canadian_arrival",
      "NOT", PropertyList["has_global_flag", "canadian_arrival_2"],
      "OR", PropertyList[
        "province_id", 9,
        "province_id", 31,
        "province_id", 37,
        "province_id", 56,
        "province_id", 267,
        "province_id", 268,
        "province_id", 303,
        "province_id", 393,
        "province_id", 396,
      ],
      "owner", PropertyList["NOT", PropertyList["culture", "canadian"]],
    ],
    "immediate", PropertyList[
      "set_global_flag", "canadian_arrival_2",
      "set_province_flag", "canadian_second_wave",
      "e_canada", PropertyList["holder_scope", PropertyList["narrative_event", PropertyList["id", "CANADA.6"]]],
    ],
    "mean_time_to_happen", PropertyList["months", 24],
    "option", PropertyList["name", "EVTOPTA_CANADA_005"],
  ],
  "narrative_event", PropertyList[
    "id", "CANADA.6",
    "title", "EVTNAME_CANADA_006",
    "desc", "EVTDESC_CANADA_006",
    "major", true,
    "hide_new", true,
    "picture", "GFX_evt_aztec_arrival",
    "border", "GFX_event_narrative_frame_war",
    "is_triggered_only", true,
    "major_trigger", PropertyList["FROM", PropertyList["owner", PropertyList["NOT", PropertyList["character", "PREVPREV"]]]],
    "immediate", PropertyList[
      "FROM", PropertyList["kingdom", PropertyList["ROOT", PropertyList["war", PropertyList[
                                                                          "casus_belli", "tribal_invasion",
                                                                          "target", "PREVPREV",
                                                                          "thirdparty_title", "PREV",
                                                                        ]]]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "canadian",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList[
                                        "horse_archers", [1500, 1500],
                                        "light_cavalry", [1500, 1500],
                                      ],
                                    ]],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
      ],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
      ],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "canadian",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList[
                                          "horse_archers", [1500, 1500],
                                          "light_cavalry", [1500, 1500],
                                        ],
                                      ]],
      ],
      "if", PropertyList[
        "limit", PropertyList["FROM", PropertyList["OR", PropertyList[
                                                     "province_id", 1,
                                                     "province_id", 9,
                                                     "province_id", 35,
                                                     "province_id", 31,
                                                   ]]],
        "FROM", PropertyList["sea_zone", PropertyList["ROOT", PropertyList["spawn_unit", PropertyList[
                                                                             "province", "PREV",
                                                                             "home", "FROM",
                                                                             "owner", "ROOT",
                                                                             "earmark", "canadian_invasion_fleet",
                                                                             "troops", PropertyList["galleys", [1000, 1000]],
                                                                           ]]]],
      ],
    ],
    "option", PropertyList["name", "EVTOPTA_CANADA_006"],
  ],
  "character_event", PropertyList[
    "id", "CANADA.100",
    "hide_window", true,
    "trigger", PropertyList[
      "has_landed_title", "e_canada",
      "NOT", PropertyList["has_global_flag", "canadian_invasion_fleet_disbanded"],
      "had_global_flag", PropertyList[
        "flag", "canadian_arrival",
        "days", 18250,
      ],
    ],
    "mean_time_to_happen", PropertyList["months", 1],
    "immediate", PropertyList[
      "disband_event_forces", "canadian_invasion_fleet",
      "set_global_flag", "canadian_invasion_fleet_disbanded",
    ],
    "option", PropertyList["name", "OK"],
  ],
  "narrative_event", PropertyList[
    "id", "CANADA.105",
    "title", "EVTNAME_CANADA_105",
    "desc", "EVTDESC_CANADA_105",
    "picture", "GFX_evt_aztec_arrival",
    "border", "GFX_event_narrative_frame_war",
    "major", true,
    "trigger", PropertyList[
      "has_global_flag", "canadian_arrival_2",
      "NOT", PropertyList["has_global_flag", "canadians_defeated"],
      "has_landed_title", "e_canada",
      "has_regiments", false,
      "is_landed", false,
    ],
    "major_trigger", PropertyList["ai", false],
    "mean_time_to_happen", PropertyList["days", 1],
    "immediate", PropertyList[
      "activate_title", PropertyList[
        "title", "e_canada",
        "status", false,
      ],
      "set_global_flag", "canadians_defeated",
    ],
    "option", PropertyList["name", "EVTOPTA_CANADA_105"],
  ],
]
