UsaInvasionEvents = PropertyList[
  "namespace", "USA",
  "province_event", PropertyList[
    "id", "USA.1",
    "desc", "EVTDESC_USA_001",
    "picture", "GFX_evt_aztec_explorers",
    "border", "GFX_event_normal_frame_war",
    "trigger", PropertyList[
      "has_dlc", "Sunset Invasion",
      "year", 1950,
      "NOT", PropertyList["year", 2050],
      "NOT", PropertyList["has_global_flag", "american_explorers"],
      "OR", PropertyList[
        "province_id", 641,
        "province_id", 649,
        "province_id", 767,
        "province_id", 789,
        "province_id", 808,
        "province_id", 819,
        "province_id", 858,
        "province_id", 861,
      ],
    ],
    "immediate", PropertyList[
      "set_global_flag", "american_explorers",
      "set_province_flag", "american_explorers",
      "activate_title", PropertyList[
        "title", "e_united_states",
        "status", true,
      ],
      "k_papal_state", PropertyList["holder_scope", PropertyList[
                                      "create_random_soldier", PropertyList[
                                        "dynasty", 1035000,
                                        "random_traits", true,
                                        "culture", "american",
                                        "religion", "protestant",
                                      ],
                                      "new_character", PropertyList[
                                        "e_united_states", PropertyList["grant_title", "PREV"],
                                        "set_government_type", "feudal_government",
                                        "set_defacto_liege", "THIS",
                                        "narrative_event", PropertyList[
                                          "id", "USA.2",
                                          "days", 7,
                                        ],
                                      ],
                                    ]],
    ],
    "mean_time_to_happen", PropertyList[
      "months", 3600,
      "modifier", PropertyList[
        "factor", 0.5,
        "year", 2000,
      ],
    ],
    "option", PropertyList["name", "EVTOPTA_USA_001"],
  ],
  "narrative_event", PropertyList[
    "id", "USA.2",
    "title", "EVTNAME_USA_002",
    "desc", "EVTDESC_USA_002",
    "major", true,
    "picture", "GFX_evt_aztec_explorers",
    "border", "GFX_event_narrative_frame_war",
    "is_triggered_only", true,
    "major_trigger", PropertyList["FROM", PropertyList["owner", PropertyList["NOT", PropertyList["character", "PREVPREV"]]]],
    "immediate", PropertyList["e_united_states", PropertyList["holder_scope", PropertyList["character_event", PropertyList["id", "CM.10018"]]]],
    "option", PropertyList["name", "EVTOPTA_USA_002"],
  ],
  "province_event", PropertyList[
    "id", "USA.3",
    "desc", "EVTDESC_USA_003",
    "picture", "GFX_evt_battle_mesoamerican",
    "border", "GFX_event_normal_frame_war",
    "trigger", PropertyList[
      "year", 1950,
      "NOT", PropertyList["has_global_flag", "american_arrival"],
      "had_province_flag", PropertyList[
        "flag", "american_explorers",
        "days", 730,
      ],
    ],
    "immediate", PropertyList[
      "set_global_flag", "american_arrival",
      "e_united_states", PropertyList["holder_scope", PropertyList["narrative_event", PropertyList["id", "USA.4"]]],
    ],
    "mean_time_to_happen", PropertyList["months", 6],
    "option", PropertyList["name", "EVTOPTA_USA_003"],
  ],
  "narrative_event", PropertyList[
    "id", "USA.4",
    "title", "EVTNAME_USA_004",
    "desc", "EVTDESC_USA_004",
    "major", true,
    "hide_new", true,
    "picture", "GFX_evt_battle_mesoamerican",
    "border", "GFX_event_narrative_frame_war",
    "is_triggered_only", true,
    "major_trigger", PropertyList["FROM", PropertyList["owner", PropertyList["NOT", PropertyList["character", "PREVPREV"]]]],
    "immediate", PropertyList[
      "any_playable_ruler", PropertyList[
        "limit", PropertyList[
          "ai", false,
          "capital_scope", PropertyList["NOT", PropertyList["region", "world_india"]],
        ],
        "character_event", PropertyList["id", "CM.10020"],
      ],
      "wealth", 10000,
      "FROM", PropertyList["kingdom", PropertyList["ROOT", PropertyList["war", PropertyList[
                                                                          "casus_belli", "tribal_invasion",
                                                                          "target", "PREVPREV",
                                                                          "thirdparty_title", "PREV",
                                                                        ]]]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 31,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 24,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 23,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 18,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 28,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 29,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
      ],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
      ],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
      ],
      "if", PropertyList[
        "limit", PropertyList["FROM", PropertyList["OR", PropertyList[
                                                     "province_id", 1,
                                                     "province_id", 9,
                                                     "province_id", 35,
                                                     "province_id", 31,
                                                   ]]],
        "FROM", PropertyList["sea_zone", PropertyList["ROOT", PropertyList["spawn_unit", PropertyList[
                                                                             "province", "PREV",
                                                                             "home", "FROM",
                                                                             "owner", "ROOT",
                                                                             "earmark", "american_invasion_fleet",
                                                                             "troops", PropertyList["galleys", [1000, 1000]],
                                                                           ]]]],
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 20,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 25,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 26,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 28,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 17,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", true,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", true,
        "age", 17,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", true,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", true,
        "age", 18,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", true,
        "age", 20,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", true,
        "age", 16,
      ],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", true,
        "age", 16,
      ],
    ],
    "option", PropertyList["name", "EVTOPTA_USA_004"],
  ],
  "province_event", PropertyList[
    "id", "USA.5",
    "desc", "EVTDESC_USA_005",
    "picture", "GFX_evt_aztec_arrival",
    "border", "GFX_event_normal_frame_war",
    "trigger", PropertyList[
      "year", 1950,
      "has_global_flag", "american_arrival",
      "NOT", PropertyList["has_global_flag", "american_arrival_2"],
      "OR", PropertyList[
        "province_id", 641,
        "province_id", 649,
        "province_id", 767,
        "province_id", 789,
        "province_id", 808,
        "province_id", 819,
        "province_id", 858,
        "province_id", 861,
      ],
      "owner", PropertyList["NOT", PropertyList["culture", "american"]],
    ],
    "immediate", PropertyList[
      "set_global_flag", "american_arrival_2",
      "set_province_flag", "american_second_wave",
      "e_united_states", PropertyList["holder_scope", PropertyList["narrative_event", PropertyList["id", "USA.6"]]],
    ],
    "mean_time_to_happen", PropertyList["months", 24],
    "option", PropertyList["name", "EVTOPTA_USA_005"],
  ],
  "narrative_event", PropertyList[
    "id", "USA.6",
    "title", "EVTNAME_USA_006",
    "desc", "EVTDESC_USA_006",
    "major", true,
    "hide_new", true,
    "picture", "GFX_evt_aztec_arrival",
    "border", "GFX_event_narrative_frame_war",
    "is_triggered_only", true,
    "major_trigger", PropertyList["FROM", PropertyList["owner", PropertyList["NOT", PropertyList["character", "PREVPREV"]]]],
    "immediate", PropertyList[
      "FROM", PropertyList["kingdom", PropertyList["ROOT", PropertyList["war", PropertyList[
                                                                          "casus_belli", "tribal_invasion",
                                                                          "target", "PREVPREV",
                                                                          "thirdparty_title", "PREV",
                                                                        ]]]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 30,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 25,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "create_character", PropertyList[
        "random_traits", true,
        "dynasty", "random",
        "religion", "protestant",
        "culture", "american",
        "female", false,
        "age", 22,
        "attributes", PropertyList["martial", 12],
        "trait", "brilliant_strategist",
      ],
      "new_character", PropertyList["spawn_unit", PropertyList[
                                      "province", "FROM",
                                      "home", "FROM",
                                      "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                    ]],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
      ],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
      ],
      "random", PropertyList[
        "chance", 50,
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 30,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 25,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
        "create_character", PropertyList[
          "random_traits", true,
          "dynasty", "random",
          "religion", "protestant",
          "culture", "american",
          "female", false,
          "age", 22,
          "attributes", PropertyList["martial", 12],
          "trait", "brilliant_strategist",
        ],
        "new_character", PropertyList["spawn_unit", PropertyList[
                                        "province", "FROM",
                                        "home", "FROM",
                                        "troops", PropertyList["heavy_infantry", [3000, 3000]],
                                      ]],
      ],
      "if", PropertyList[
        "limit", PropertyList["FROM", PropertyList["OR", PropertyList[
                                                     "province_id", 1,
                                                     "province_id", 9,
                                                     "province_id", 35,
                                                     "province_id", 31,
                                                   ]]],
        "FROM", PropertyList["sea_zone", PropertyList["ROOT", PropertyList["spawn_unit", PropertyList[
                                                                             "province", "PREV",
                                                                             "home", "FROM",
                                                                             "owner", "ROOT",
                                                                             "earmark", "american_invasion_fleet",
                                                                             "troops", PropertyList["galleys", [1000, 1000]],
                                                                           ]]]],
      ],
    ],
    "option", PropertyList["name", "EVTOPTA_USA_006"],
  ],
  "character_event", PropertyList[
    "id", "USA.100",
    "hide_window", true,
    "trigger", PropertyList[
      "has_landed_title", "e_united_states",
      "NOT", PropertyList["has_global_flag", "american_invasion_fleet_disbanded"],
      "had_global_flag", PropertyList[
        "flag", "american_arrival",
        "days", 18250,
      ],
    ],
    "mean_time_to_happen", PropertyList["months", 1],
    "immediate", PropertyList[
      "disband_event_forces", "american_invasion_fleet",
      "set_global_flag", "american_invasion_fleet_disbanded",
    ],
    "option", PropertyList["name", "OK"],
  ],
  "narrative_event", PropertyList[
    "id", "USA.105",
    "title", "EVTNAME_USA_105",
    "desc", "EVTDESC_USA_105",
    "picture", "GFX_evt_aztec_arrival",
    "border", "GFX_event_narrative_frame_war",
    "major", true,
    "trigger", PropertyList[
      "has_global_flag", "american_arrival_2",
      "NOT", PropertyList["has_global_flag", "americans_defeated"],
      "has_landed_title", "e_united_states",
      "has_regiments", false,
      "is_landed", false,
    ],
    "major_trigger", PropertyList["ai", false],
    "mean_time_to_happen", PropertyList["days", 1],
    "immediate", PropertyList[
      "activate_title", PropertyList[
        "title", "e_united_states",
        "status", false,
      ],
      "set_global_flag", "americans_defeated",
    ],
    "option", PropertyList["name", "EVTOPTA_USA_105"],
  ],
]
