<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>brackets</key>
	<array>
		<dict>
			<key>match</key>
			<string>\}</string>
			<key>name</key>
			<string>keyword.operator.paradox</string>
			<key>pop</key>
			<true/>
		</dict>
		<dict>
			<key>include</key>
			<string>main</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
		<string>mod</string>
	</array>
	<key>name</key>
	<string>Paradox</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(OR|AND|NOT|NAND|NOR)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.paradox</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ROOT|(?:FROM)+|(?:PREV)+)\b</string>
			<key>name</key>
			<string>keyword.operator.paradox</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#.*$\n?</string>
			<key>name</key>
			<string>comment.line.percent-sign</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(yes|no)\b</string>
			<key>name</key>
			<string>constant.language.paradox</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.paradox</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"(.*?)\"</string>
			<key>name</key>
			<string>string.double.paradox</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\.\d+\.\d+\b</string>
			<key>name</key>
			<string>constant.numeric.date</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?\b[0-9]+(?:\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{</string>
			<key>name</key>
			<string>keyword.operator.paradox</string>
			<key>push</key>
			<string>brackets</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\}</string>
			<key>name</key>
			<string>keyword.operator.paradox</string>
			<key>scope</key>
			<string>invalid.illegal.stray-bracket-end</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.paradox</string>
	<key>uuid</key>
	<string>ac3e3123-a3f4-4281-93aa-3b40351ce18b</string>
</dict>
</plist>
