#!/usr/bin/env ruby

require "RMagick"
require_relative "../lib/paradox"
require_relative "game_map"
require "pry"

class DrawSeaLandMap < ParadoxGame
  include GameMap

  def run!
    generate_map_image(land_sea_color_map).write("sea_land_map.png")
  end
end

DrawSeaLandMap.new(*ARGV).run!
