#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
Pathname(__dir__).glob("mods/*.rb").each{|rb| require_relative rb}

class FunAndBalanceETModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/eu4-1.27.2",
        "source/ExtendedTimeline 1.8.4/ExtendedTimeline.mod"
      ),
      "output/fun_and_balance_et"
    )
  end
  def build_mod_files!
    apply_modifications! FunAndBalanceETGameModification,
                         ReligiousLeaguesGameModification,
                         NationCustomizerGameModification,
                         ChangeGovernmentGameModification
    create_mod_descriptor!(
      # name starts with space to make sure it is alphabetically before "Extended Timeline"
      # space used to work, but Steam started stripping it
      name: "!Fun and Balance for Extended Timeline",
      path: "mod/fun_and_balance_et",
      supported_version: "1.27",
      picture: "fun_and_balance_et.jpg",
    )
  end
end

FunAndBalanceETModBuilder.new.build!
