#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
require_relative "./fun_and_balance_common"

class FunAndBalanceETModBuilder < ParadoxModBuilder
  include FunAndBalanceCommon

  def fix_adopt_secularism_decision!
    patch_mod_file!("decisions/et_conversion_decisions.txt") do |node|
      node["religion_decisions"]["adopt_secularism"]["allow"].add! "is_subject", false
    end
  end

  def hire_merc_company_decision!
    create_mod_file! "common/event_modifiers/private_military_company.txt", PropertyList[
      "recently_hired_mercs", PropertyList[],
    ]
    create_mod_file! "decisions/private_military_company.txt", PropertyList[
      "country_decisions", PropertyList[
        "hire_merc_company", PropertyList[
          "potential", PropertyList[
            "year", 1900,
          ],
          "allow", PropertyList[
            "treasury", 1000,
            Property::NOT["has_country_modifier", "recently_hired_mercs"],
            Property::NOT["num_of_loans", 5],
            Property::NOT["manpower_percentage", 0.10],
            Property::OR[
              "is_at_war", true,
              "num_of_revolts", 1,
            ],
          ],
          "effect", PropertyList[
            "add_treasury", -1000,
            "add_manpower", 20,
            "add_country_modifier", PropertyList[
              "name", "recently_hired_mercs",
              "duration", 365*5,
            ],
          ],
          "ai_will_do", PropertyList["factor", 1],
        ]
      ]
    ]
    localization! "private_military_company",
      "recently_hired_mercs"    => "Recently hired private military company",
      "hire_merc_company_title" => "Employ private military company",
      "hire_merc_company_desc"  => "Private military companies can supplement your manpower"
  end

  def build_mod_files!
    # Fix syntax errors
    patch_file!("common/ideas/et_country_ideas.txt", force_create: true) do |content|
      content.sub(/top_five_in_literacy\s*$/, "top_five_in_literacy = {")
    end

    patch_defines_lua!([
      ["SCALED_TRUCE_YEARS", 10, 0],
      ["ANNEX_DIP_COST_PER_BASE_TAX", 10, 1],
      ["INTEGRATE_VASSAL_MIN_YEARS", 10, 20],
      ["POLICY_COST", 1, 0],
      ["FOREIGN_REBEL_SUPPORT", 4, 6],
      ["WESTERN_POWER_TICK_REDUCTION_FACTOR", 15, 1000000],
      ["ADVISOR_COST_INCREASE_PER_YEAR", 0.0005,  0.0005],
      ["CULTURE_GAIN_THRESHOLD", "0.20", "0.10"],
      ["POWER_MAX", 999, 1500],
      ["PS_BUILD_BUILDING", 10, 5],
      ["PS_MOVE_CAPITAL", 200, 100],
      ["PS_MOVE_TRADE_PORT", 300, 100],
      ["PS_CHANGE_CULTURE", 40, 15],
      ["CORE_LOSE", 50, 100],
      ["CORE_LOSE_CULTURE_GROUP", 150, 300],
      ["PROTECTORATE_TECH_THRESHOLD", 0.25, 5.0],
      ["PROTECTORATE_LOWER_BOUND", 0.5, 5.0],
      ["VASSAL_FABRICATE_CLAIMS", 1, 1],
      ["AI_BUY_PROVINCE_SUBJECT_MAX_OE", 50, 50],
      ["VASSALIZE_BASE_TAX_CAP", 40, 10000],
      ["PEACE_TIME_EARLY_FACTOR", 0.75, 0.50],
      ["PEACE_WAR_EXHAUSTION_FACTOR", 1.0, 2.0],
      ["TECH_AHEAD_OF_TIME", 0.1, 0.05],
      ["MONTHS_BEFORE_TOTAL_OCCUPATION", 60, 24],
      ["AUTONOMY_AT_DIPLO_ANNEX", 75, 50],
      ["RANDOM_LUCKY_TAX_WEIGHT", 1, 0],
      ["RANDOM_LUCKY_TECH_WEIGHT", 1, 0],
      ["RANDOM_LUCKY_SLOW_TECH_PENALTY", 0.33, 1],
      ["DIPLOMATIC_INTEREST_DISTANCE", 150, 250],
      ["MAX_DISTANCE_TO_OWNER_AREA", 200, 1000],
      ["PROVINCE_BUILDING_LEVEL_THRESHOLD", 5, 7], # For late game money sink
      ["RULER_BASE_SKILL", 2, 3],
      ["IDEAS_MAX_LEVEL", 4, 10],
      ["IDEAS_PERCENTAGE_LIMIT", 50, 100],
      ["MAX_IDEA_GROUPS_FROM_SAME_CATEGORY", 0.5, 1.0],
      ["OVERSEAS_DISTANCE", 150, 400],
    ])

    patch_mod_file!("common/static_modifiers/00_static_modifiers.txt") do |node|
      node["war"] = PropertyList[] if node["war"] == []
      modify_node! node,
        ["base_values", "diplomatic_upkeep", 4, 8],
        ["war", "war_exhaustion_cost", nil, 100],
        ["emperor", "diplomatic_upkeep", 1, 2],
        ["war_exhaustion", "defensiveness", nil, -0.02],
        ["war_exhaustion", "land_morale", nil, -0.02],
        ["war_exhaustion", "naval_morale", nil, -0.02],
        ["num_of_marriages", "heir_chance", 0.05, 0.03]
    end

    change_elections_to_eu3_style!
    dont_destroy_buildings_on_conquest!
    double_diplo_rel_limit_from_ideas!
    fix_opinions!
    fix_wargoals!
    no_naval_attrition!
    reduce_religious_center_penalty!
    disable_burgundy_inheritance!
    move_burgundy_capital_to_hre!
    smooth_oe_scaling!
    fix_adopt_secularism_decision!
    hire_merc_company_decision!
    easier_change_government_decisions!
    fix_custom_ideas!
    power_projection_tweaks!
    build_mod_config_menu_for_et!
    more_options_for_religious_leagues!
    improve_mission_pool!
  end
end

mb = FunAndBalanceETModBuilder.new(
  ParadoxGame.new(
    "source/eu4-1.11.1",
    "source/ExtendedTimeline 0.12.3/ExtendedTimeline"
  ),
  "output/fun_and_balance_et"
)
mb.build!
