#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
Pathname(__dir__).glob("mods/*.rb").each{|rb| require_relative rb}

class FunAndBalanceETModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/eu4-1.21.1",
        "source/ExtendedTimeline 1.4.4/ExtendedTimeline.mod"
      ),
      "output/fun_and_balance_et"
    )
  end
  def build_mod_files!
    apply_modifications! FunAndBalanceETGameModification,
                         HolySitesETGameModification,
                         ReligiousLeaguesGameModification,
                         NationCustomizerGameModification,
                         # No achievements - map would need too many fixes
                         # No extra foramble countries, makes little sense it this mod
                         EU3StyleElectionsGameModification,
                         # ImproveMissionsGameModification - it could get ported to ET eventually
                         HideCancelledMissionsGameModification,
                         ConfigMenuETGameModification,
                         ChangeGovernmentGameModification
    create_mod_descriptor!(
      # name starts with space to make sure it is alphabetically before "Extended Timeline"
      # space used to work, but Steam started stripping it
      name: "!Fun and Balance for Extended Timeline",
      path: "mod/fun_and_balance_et",
      supported_version: "1.21",
      picture: "fun_and_balance_et.jpg",
    )
  end
end

if __FILE__ == $0
  FunAndBalanceETModBuilder.new.build!
end
