#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
require_relative "./fun_and_balance_common"

class FunAndBalanceShatteredEuropeModBuilder < ParadoxModBuilder
  include FunAndBalanceCommon

  def build_mod_files!
    patch_defines_lua!([
      ["SCALED_TRUCE_YEARS", 10, 0],
      ["ANNEX_DIP_COST_PER_BASE_TAX", 10, 1],
      ["INTEGRATE_VASSAL_MIN_YEARS", 10, 20],
      ["POLICY_COST", 1, 0],
      ["FOREIGN_REBEL_SUPPORT", 4, 6],
      ["WESTERN_POWER_TICK_REDUCTION_FACTOR", 15, 1000000],
      ["ADVISOR_COST_INCREASE_PER_YEAR", 0.01,  0.005],
      ["CULTURE_GAIN_THRESHOLD", "0.20", "0.10"],
      ["POWER_MAX", 999, 1500],
      ["PS_BUILD_BUILDING", 10, 5],
      ["PS_MOVE_TRADE_PORT", 300, 100],
      ["PS_CHANGE_CULTURE", 25, 10],
      ["CLAIM_LOSE", 25, 50],
      ["CORE_LOSE", 50, 100],
      ["CORE_LOSE_CULTURE_GROUP", 150, 300],
      ["PROTECTORATE_TECH_THRESHOLD", 0.5, 5.0],
      ["PROTECTORATE_LOWER_BOUND", 0.5, 5.0],
      ["VASSALIZE_BASE_TAX_CAP", 40, 10000],
      ["PEACE_TIME_EARLY_FACTOR", 0.75, 0.50],
      ["PEACE_WAR_EXHAUSTION_FACTOR", 1.0, 2.0],
      ["TECH_AHEAD_OF_TIME", 0.1, 0.05],
      ["MONTHS_BEFORE_TOTAL_OCCUPATION", 60, 24],
      ["AUTONOMY_AT_DIPLO_ANNEX", 75, 50],
      ["RANDOM_LUCKY_TAX_WEIGHT", 1, 0],
      ["RANDOM_LUCKY_TECH_WEIGHT", 1, 0],
      ["RANDOM_LUCKY_SLOW_TECH_PENALTY", 0.33, 1],
      ["DIPLOMATIC_INTEREST_DISTANCE", 150, 250],
      ["MAX_DISTANCE_TO_OWNER_AREA", 200, 1000],
      ["RULER_BASE_SKILL", 2, 3],
      ["IDEAS_MAX_LEVEL", 4, 10],
      ["IDEAS_PERCENTAGE_LIMIT", 50, 100],
      ["MAX_IDEA_GROUPS_FROM_SAME_CATEGORY", 0.5, 1.0],
      ["OVERSEAS_DISTANCE", 150, 400],
    ])

    patch_mod_file!("common/static_modifiers/00_static_modifiers.txt") do |node|
      unless node["base_values"]["global_missionary_strength"] == 0.02
        raise "Expect base missionary strength to equal 2%"
      end
      node["base_values"]["diplomatic_upkeep"] = 8
      node["base_values"]["global_missionary_strength"] = 0.01
      node["base_values"]["global_heretic_missionary_strength"] = 0.01
      node["war"] = PropertyList[] if node["war"] == []
      node["war"]["war_exhaustion_cost"] = 100
      node["emperor"]["diplomatic_upkeep"] = 2
      node["war_exhaustion"]["defensiveness"] = -0.02
      node["war_exhaustion"]["land_morale"] = -0.02
      node["war_exhaustion"]["naval_morale"] = -0.02
      node["num_of_marriages"]["heir_change"] = 0.03
    end

    anyone_can_form_byzantium!
    change_elections_to_eu3_style!
    dont_destroy_buildings_on_conquest!
    double_diplo_rel_limit_from_ideas!
    feature_extra_formable_countries!
    feature_holy_sites!
    feature_partial_westernization!
    fix_opinions!
    fix_wargoals!
    no_naval_attrition!
    patch_religion!
    reduce_religious_center_penalty!
    disable_burgundy_inheritance!
    reverse_horde_nerfs!
    smooth_oe_scaling!
    make_missions_not_tag_specific!
    easier_change_government_decisions!
    fix_custom_ideas!
    power_projection_tweaks!
    build_mod_config_menu_for_vanilla!
  end
end

mb = FunAndBalanceShatteredEuropeModBuilder.new(
  ParadoxGame.new(
    "source/eu4-1.11.1",
    "source/ShatteredEurope-forked/ShatteredEurope",
  ),
  "output/fun_and_balance_shattered_europe"
)
mb.build!
