#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
Pathname(__dir__).glob("mods/*.rb").each{|rb| require_relative rb}

class FunAndBalanceModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/eu4-1.26.1",
      ),
      "output/fun_and_balance",
    )
  end
  def build_mod_files!
    apply_modifications! DisableNormalOrHistoricalCheck,
                         FunAndBalanceGameModification,
                         HolySitesVanillaGameModification,
                         ReligiousLeaguesGameModification,
                         NationCustomizerGameModification,
                         ExtraFormableCountriesGameModification,
                         EU3StyleElectionsGameModification,
                         ConfigMenuVanillaGameModification
                         ChangeGovernmentGameModification
    create_mod_descriptor!(
      name: "Fun and Balance",
      path: "mod/fun_and_balance",
      supported_version: "1.26",
      picture: "fun_and_balance.jpg",
    )
  end
end

FunAndBalanceModBuilder.new.build!
