#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
require_relative "./fun_and_balance_common"

class FunAndBalanceShatteredEuropeModBuilder < ParadoxModBuilder
  include FunAndBalanceCommon

  # Many files in ShatteredEurope are broken
  def fix_syntax!
    # This edit happens on same line as } far too often, breaking files
    [
      "history/provinces/169 - Armor.txt",
      "history/provinces/170 - Finistere.txt",
      "history/provinces/171 - Morbihan.txt",
      "history/provinces/172 - Vendee.txt",
      "history/provinces/1861 - Derby.txt",
      "history/provinces/233 - Cornwall.txt",
      "history/provinces/234 - Wessex.txt",
      "history/provinces/239 - Gloucestershire.txt",
      "history/provinces/240 - Marches.txt",
      "history/provinces/241 - Glamorgan.txt",
      "history/provinces/242 - Gwynedd.txt",
      "history/provinces/243 - lincoln.txt",
      "history/provinces/245 - Yorkshire.txt",
      "history/provinces/246 - Northumberland.txt",
      "history/provinces/247 - Cumbria.txt",
      "history/provinces/249 - Ayrshire.txt",
      "history/provinces/252 - Highlands.txt",
      "history/provinces/253 - Western Isles.txt",
      "history/provinces/372 - ulster.txt",
      "history/provinces/373 - meath.txt",
      "history/provinces/374 - leinster.txt",
      "history/provinces/375 - munster.txt",
      "history/provinces/376 - connaught.txt",
    ].each do |name|
      patch_file!(name, force_create: true, reencode: true) do |content|
        content.gsub("#Possibly druidic in future, mass edit", "")
      end
    end
    patch_file!("history/provinces/378 - beirut.txt", force_create: true, reencode: true) do |content|
      content.sub("remove_core = KOJ", "remove_core = KOJ }")
    end
    # Weird encoding issues, best to just force ASCII
    patch_file!("common/countries/AlAndalus.txt", force_create: true) do |content|
      content.encode("UTF-8-MAC").gsub(/[^\000-\177]/, "")
    end
    patch_file!("history/countries/NOR - Norway.txt", force_create: true) do |content|
      content.encode("UTF-8-MAC").gsub(/[^\000-\177]/, "")
    end
    patch_file!("missions/iberian_missions.txt", force_create: true, reencode: true) do |content|
      # What is that even trying to do...
      content.gsub(/\bnot\b/, "NOT").gsub(/\bthis\b/i, "ROOT").gsub(/\bally\b/, "any_ally")
    end
  end

  def remove_cot_tag!
    patch_mod_files!("history/provinces/*.txt") do |node|
      node.delete "cot"
      node.each do |key, val|
        if key.is_a?(Date) and val.is_a?(PropertyList)
          val.delete "cot"
        end
      end
      node.delete_if do |key, val|
        key.is_a?(Date) and val.is_a?(PropertyList) and val.empty?
      end
    end
  end

  def add_missing_province_modifiers!
    [
      ["history/provinces/101 - Liguria.txt", "center_of_trade_modifier"],
      ["history/provinces/112 - Venezia.txt", "center_of_trade_modifier"],
      ["history/provinces/113 - Ferrara.txt", "po_estuary_modifier"],
      ["history/provinces/118 - Roma.txt", "religious_center"],
      ["history/provinces/134 - Wien.txt", "center_of_trade_modifier"],
      ["history/provinces/137 - Ragusa.txt", "center_of_trade_modifier"],
      ["history/provinces/151 - Thrace.txt", "center_of_trade_modifier", "bosphorous_sound_toll"],
      ["history/provinces/167 - Caux.txt", "seine_estuary_modifier"],
      ["history/provinces/172 - Vendee.txt", "loire_estuary_modifier"],
      ["history/provinces/174 - Gascogne.txt", "gironde_estuary_modifier"],
      ["history/provinces/1744 - Antwerpen.txt", "center_of_trade_modifier"],
      ["history/provinces/1756 - Budjak.txt", "danube_estuary_modifier"],
      ["history/provinces/183 - Ile-de-France.txt", "center_of_trade_modifier"],
      ["history/provinces/1858 - Stettin.txt", "oder_estuary_modifier"],
      ["history/provinces/1874 - Bremen.txt", "weser_estuary_modifier"],
      ["history/provinces/1876 - Frankfurt.txt", "center_of_trade_modifier"],
      ["history/provinces/201 - Provence.txt", "rhone_estuary_modifier", "center_of_trade_modifier"],
      ["history/provinces/213 - Barcelona.txt", "ebro_estuary_modifier"],
      ["history/provinces/220 - Valencia.txt", "center_of_trade_modifier"],
      ["history/provinces/224 - Andalucia.txt", "guadiana_estuary_modifier", "center_of_trade_modifier"],
      ["history/provinces/227 - Lisboa.txt", "tagus_estuary_modifier", "center_of_trade_modifier"],
      ["history/provinces/231 - Porto.txt", "douro_estuary_modifier"],
      ["history/provinces/236 - London.txt", "thames_estuary_modifier", "center_of_trade_modifier"],
      ["history/provinces/262 - Krakow.txt", "center_of_trade_modifier"],
      ["history/provinces/280 - Kiev.txt", "center_of_trade_modifier"],
      ["history/provinces/282 - Yedisan.txt", "dnestr_estuary_modifier"],
      ["history/provinces/285 - Kaffa.txt", "center_of_trade_modifier"],
      ["history/provinces/286 - Azow.txt", "don_estuary_modifier"],
      ["history/provinces/295 - Moskva.txt", "center_of_trade_modifier"],
      ["history/provinces/310 - Novgorod.txt", "center_of_trade_modifier"],
      ["history/provinces/313 - Archangelsk.txt", "center_of_trade_modifier"],
      ["history/provinces/377 - Aleppo.txt", "center_of_trade_modifier"],
      ["history/provinces/38 - Riga.txt", "daugava_estuary_modifier"],
      ["history/provinces/41 - Ostpreussen.txt", "neman_estuary_modifier"],
      ["history/provinces/43 - Danzig.txt", "vistula_estuary_modifier", "center_of_trade_modifier"],
      ["history/provinces/44 - Hamburg.txt", "elbe_estuary_modifier", "center_of_trade_modifier"],
      ["history/provinces/45 - Lubeck.txt", "center_of_trade_modifier"],
      ["history/provinces/97 - Holland.txt", "center_of_trade_modifier", "rhine_estuary_modifier"],
    ].each do |path, *mods|
      patch_mod_file!(path) do |node|
        d1000 = Date.new(1000, 1, 1, Date::JULIAN)
        node[d1000] = PropertyList[
          *mods.map{|mod|
            Property[
              "add_permanent_province_modifier", PropertyList[
                "name", mod,
                "duration", -1,
              ]
            ]
          }
        ]
      end
    end
  end

  def build_mod_files!
    fix_syntax!

    patch_defines_lua!([
      ["SCALED_TRUCE_YEARS", 10, 0],
      ["ANNEX_DIP_COST_PER_BASE_TAX", 15, 1],
      ["MAX_ACTIVE_POLICIES", 5, 10],
      ["POLICY_COST", 1, 0],
      ["FOREIGN_REBEL_SUPPORT", 4, 6],
      ["WESTERN_POWER_TICK_REDUCTION_FACTOR", 15, 1000000],
      ["ADVISOR_COST_INCREASE_PER_YEAR", 0.01,  0.005],
      ["CULTURE_GAIN_THRESHOLD", "0.20", "0.10"],
      ["POWER_MAX", 999, 1500],
      ["PS_BUILD_BUILDING", 10, 5],
      ["PS_MOVE_TRADE_PORT", 300, 100],
      ["PS_CHANGE_CULTURE", 25, 10],
      ["CLAIM_LOSE", 25, 50],
      ["CORE_LOSE", 50, 100],
      ["CORE_LOSE_CULTURE_GROUP", 150, 300],
      ["CORE_TIME_SIZE_MODIFIER", 0.04, 0.0],
      ["PROTECTORATE_TECH_THRESHOLD", 0.5, 5.0],
      ["PROTECTORATE_LOWER_BOUND", 0.5, 5.0],
      ["VASSAL_FABRICATE_CLAIMS", 0, 1],
      ["AI_BUY_PROVINCE_SUBJECT_MAX_OE", 0, 50],
      ["VASSALIZE_BASE_TAX_CAP", 40, 10000],
      ["GREAT_POWER_ALLIANCE_PENALTY", 50, 25],
      ["PEACE_TIME_EARLY_FACTOR", 0.75, 0.50],
      ["PEACE_WAR_EXHAUSTION_FACTOR", 1.0, 2.0],
      ["TECH_AHEAD_OF_TIME", 0.1, 0.05],
    ])

    patch_mod_file!("common/static_modifiers/00_static_modifiers.txt") do |node|
      unless node["base_values"]["global_missionary_strength"] == 0.02
        raise "Expect base missionary strength to equal 2%"
      end
      node["base_values"]["diplomatic_upkeep"] = 8
      node["base_values"]["global_missionary_strength"] = 0.01
      node["base_values"]["global_heretic_missionary_strength"] = 0.01
      node["war"] = PropertyList[] if node["war"] == []
      node["war"]["war_exhaustion_cost"] = 100
      node["emperor"]["diplomatic_upkeep"] = 2
      node["inverse_religious_unity"]["global_revolt_risk"] = 5
      node["war_exhaustion"]["defensiveness"] = -0.02
      node["war_exhaustion"]["land_morale"] = -0.02
      node["war_exhaustion"]["naval_morale"] = -0.02
      node["non_accepted_culture"]["local_revolt_risk"] = 4
    end

    always_display_policies!
    anyone_can_form_byzantium!
    change_elections_to_eu3_style!
    dont_destroy_buildings_on_conquest!
    double_diplo_rel_limit_from_ideas!
    feature_extra_formable_countries!
    feature_holy_sites!
    feature_partial_westernization!
    feature_return_vassal_cores!
    fix_opinions!
    fix_peasant_war!
    fix_wargoals!
    no_naval_attrition!
    patch_religion!
    reduce_religious_center_penalty!
    restore_hre_ia_on_prince_religion_change!
    remove_burgundy_inheritance!
    reverse_horde_nerfs!
    smooth_oe_scaling!
    make_missions_not_tag_specific!
    rescale_tech_times_to_1399_1820_timeframe!
    remove_cot_tag!
    add_missing_province_modifiers!
  end
end

mb = FunAndBalanceShatteredEuropeModBuilder.new(
  ParadoxGame.new("eu4", "source/ShatteredEurope/ShatteredEurope"),
  "output/fun_and_balance_shattered_europe"
)
mb.build!
