#!/usr/bin/env ruby

require_relative "../lib/paradox_mod_builder"
Pathname(__dir__).glob("mods/*.rb").each{|rb| require_relative rb}

class FunAndBalanceModBuilder < ParadoxModBuilder
  def initialize
    super(
      ParadoxGame.new(
        "source/eu4-1.27.2",
        "source/1356",
      ),
      "output/fun_and_balance_1356",
    )
  end

  def build_mod_files!
    apply_modifications! FunAndBalance1356GameModification,
                         NationCustomizerGameModification
    create_mod_descriptor!(
      name: "!Fun and Balance for 1356",
      path: "mod/fun_and_balance_1356",
      supported_version: "1.27",
      picture: "fun_and_balance_1356.jpg",
    )
  end
end

FunAndBalanceModBuilder.new.build!
