#!/usr/bin/env ruby

require "pathname"
require "fileutils"

system "trash", "build" if Pathname("build").exist?

Pathname("build").mkpath
Pathname("build/fun_and_balance_shattered_europe").mkpath

system "cp fun_and_balance/fun_and_balance_et.mod build/"
system "cp -a output/fun_and_balance_shattered_europe/* build/fun_and_balance_shattered_europe/"
Dir.chdir("build") do
  system "7za a fun_and_balance_0.13_for_eu4_1.7.3_and_shattered_europe.7z"
end
