#!/usr/bin/env ruby

require "pathname"

class Pathname
  def write(content)
    open('wb') do |fh|
      fh.write(content)
    end
  end

  def patch
    content = read
    updated = yield(content.dup)
    if updated != content
      write(updated)
    end
    self
  end
end

base = Pathname(ARGV[0])
(base + "common/policies").children.each do |c|
  c.patch do |content|
    content.gsub("has_idea_group = ", "# has_idea_group = ")
  end
end
