#!/usr/bin/env ruby

require_relative "./eu4_analysis"
require_relative "custom_ideas"
require "simplex"

class AnalyzeCustomIdeaBonuses < EU4Analysis
  include CustomIdeas

  def call
    print_best_free_ideas!
    print_scores!
    [0, 50, 100, 150, 200, 300, 400, 600, 800].each do |max_cost|
      puts ""
      puts "Simplex for cost=#{max_cost}"
      run_simplex!(max_cost)
    end
  end

  def print_scores!
    custom_ideas.each do |idea_name, idea, idea_score, category, levels|
      puts [idea_score, idea.inspect, category, levels.inspect].join("\t")
    end
  end

  def print_best_free_ideas!
    ["ADM", "DIP", "MIL"].each do |cat|
      puts "Best free ideas in #{cat}:"
      custom_ideas.select{ _5[0] == 0 and _4 == cat}.sort_by{ -_3 }.each do |idea_name, idea, idea_score, category, levels|
        puts [idea_score, idea.inspect, category].join("\t")
      end
      puts ""
    end
  end

  def run_simplex!(max_cost)
    ideas_to_consider = custom_ideas[0,100]
    max_ideas = 10

    values  = []
    weights = []
    labels  = []
    index_ranges = []

    objective = []
    lhs = []
    rhs = []

    ideas_to_consider.each do |idea_name, idea, idea_score, category, levels|
      # Manually force max 1 diplomat as extra ones rapidly lose value
      if idea_name == "custom_idea_diplomats"
        levels = levels[0,1]
      end
      # It makes no sense totake both inf and cav bonus, so just take inf bonus
      next if idea_name == "custom_cavalry_shock"
      next if idea_name == "custom_cavalry_fire"
      index_ranges << (objective.size...objective.size + levels.size)
      levels.each_with_index do |level_cost, level_i|
        objective    << (idea_score * (level_i+1)).round(3)
        weights      << level_cost
        labels       << "#{idea_name} #{level_i+1}"
      end
    end

    # Max picks
    lhs << [1] * objective.size
    rhs << max_ideas

    # Max cost
    lhs << weights
    rhs << max_cost

    # Can't pick anything > 1
    labels.size.times do |i|
      lhs << (0...labels.size).map{|u| u == i ? 1 : 0}
      rhs << 1
    end

    # Can't pick multiple choices from same bonus
    # TODO
    index_ranges.each do |range|
      lhs << (0...labels.size).map{|u| range.include?(u) ? 1 : 0}
      rhs << 1
    end

    simplex = Simplex.new(objective, lhs, rhs)
    solution = simplex.solution

    # Print solution, might not be integery
    solution_full = solution.zip(labels).zip(weights).zip(objective).map(&:flatten).select{|c,| c > 0}
    pp solution_full.map{|u,*x| [u.to_i == u ? u.to_i : u, *x]}
    puts "Total cost: #{solution_full.map{|u|u[2]*u[0]}.inject(&:+)}"
    puts "Total value: #{solution_full.map{|u|u[3]*u[0]}.inject(&:+).round(3)}"
  end

end

AnalyzeCustomIdeaBonuses.new_from_argv.call
