#!/usr/bin/env ruby

require "set"
require "pp"
require "pathname"
require_relative "../lib/paradox"
require_relative "bonus_scoring"

class AnalyzeIdeaGroups < ParadoxGame
  def each_idea_group
    glob("common/ideas/*").each do |path|
      parse(path).each do |name, idea_group|
        if @ideas == "national"
          next if idea_group["category"]
        elsif @ideas == "basic"
          next unless idea_group["category"]
        end
        yield(name, idea_group)
      end
    end
  end

  def list_of_bonuses(idea_group)
    idea_group = idea_group.to_h
    idea_group.delete "category"
    idea_group.delete "trigger"
    idea_group.delete "ai_will_do"
    idea_group.delete "free"
    idea_group.delete "important"

    bonuses = BonusScoring.new
    idea_group.each do |_,idea|
      idea.each do |k,v|
        bonuses.send(k,v)
      end
    end
    bonuses
  end

  def analyze_idea_groups!
    output = []
    each_idea_group do |name, idea_group|
      bonuses = list_of_bonuses(idea_group)
      output << [bonuses.score, localization(name)]
    end
    output.sort_by{|s,n| [-s,n]}.each do |score, name|
      puts "%.2f %s" % [score, name]
    end
  end

  def initialize(ideas, *paths)
    @ideas = ideas
    super(*paths)
  end
end

ideas = "all"
if ARGV[0] =~ /\A--(.*)/
  ideas = $1
  ARGV.shift
end

AnalyzeIdeaGroups.new(ideas, *ARGV).analyze_idea_groups!
