#!/usr/bin/env ruby

require "csv"
require_relative "./eu4_analysis"

class AnalyzeUnitPips < EU4Analysis
  def units
    unless @units
      @units = {}
      glob("common/units/*.txt").each do |c|
        @units[c.basename(".txt").to_s] = parse_unit_file(c)
      end
    end
    @units
  end

  def mil_tech
    unless @mil_tech
      @mil_tech = parse("common/technologies/mil.txt").find_all("technology").map do |tech|
        tech.find_all("enable")
      end
    end
    @mil_tech
  end

  def best_unit(tech_level, type, tech_group)
    units_enabled_up_to_mil_tech(tech_level).select{|unit|
      unit["type"] == type and unit["unit_type"] == tech_group
    }.max_by{|unit| unit["total_pips"]}
  end

  def unit_tech_groups
    @unit_tech_groups ||= units.values.map{|u| u["unit_type"]}.compact.uniq.sort
  end

  def units_enabled_up_to_mil_tech(tech_level)
    mil_tech[0..tech_level].flatten.map{|name|
      units[name]
    }
  end

  def generate_report_for_best_units(type)
    relevant_tech_groups = [nil, *unit_tech_groups].select{|tg|
      !!best_unit(999, type, tg)
    }
    CSV(STDOUT.dup) do |csv|
      csv << [type.capitalize]
      csv << ["Tech", *relevant_tech_groups]
      mil_tech.each_with_index do |tech, i|
        csv << [i,
          *relevant_tech_groups.map{|tg|
            unit = best_unit(i, type, tg)
            unit && unit["total_pips"]
          }
        ]
      end
      csv << []
    end
  end

  def call
    generate_report_for_best_units "infantry"
    generate_report_for_best_units "cavalry"
    generate_report_for_best_units "artillery"
  end

  private

  def parse_unit_file(path)
    unit = parse(path).to_h
    if %W[infantry cavalry artillery].include?(unit["type"])
      unit["total_pips"] = unit["offensive_morale"] +
                           unit["defensive_morale"] +
                           unit["offensive_fire"] +
                           unit["defensive_fire"] +
                           unit["offensive_shock"] +
                           unit["defensive_shock"]
    end
    unit
  end
end

AnalyzeUnitPips.new_from_argv.call
