#!/usr/bin/env ruby

require_relative "./eu4_analysis"
require_relative "bonus_scoring"

class AnalyzePolicies < EU4Analysis
  def each_policy
    glob("common/policies/*").each do |path|
      parse(path).each do |name, policy|
        yield(name, policy)
      end
    end
  end

  def call
    results = []
    each_policy do |name, policy|
      policy = policy.to_h
      point_type = policy["monarch_power"].downcase
      policy.delete("potential")
      policy.delete("monarch_power")
      policy.delete("ai_will_do")
      requirements = policy.delete("allow").to_h["full_idea_group"].map{|i| i.sub("_ideas", "")}

      bonuses = BonusScoring.new(policy)
      # Some are free, so biasing is no longer great idea
      # bonuses.send("monthly_#{point_type}_points", -1.0)
      results << [bonuses.score, name, *requirements, point_type, policy.inspect]
    end
    puts results.sort.map{|r| r.join(" ")}
  end
end

AnalyzePolicies.new_from_argv.call
