#!/usr/bin/env ruby

require_relative "../lib/paradox"

class CountryPrimaryCultures < ParadoxGame
  def each_country_primary_culture
    parse("common/cultures/00_cultures.txt").each do |group_name, group|
      group = group.to_h
      group.delete "graphical_culture"
      group.delete "dynasty_names"
      group.each do |culture_name, details|
        next if details.is_a?(Array)
        details = details.to_h
        details.delete "dynasty_names"
        yield culture_name, details["primary"]
      end
    end
  end
end

if $0 == __FILE__
  CountryPrimaryCultures.new(*ARGV).each_country_primary_culture do |culture_name, primary_tag|
    puts [primary_tag, culture_name].join("\t")
  end
end
