#!/usr/bin/env ruby

require_relative "./eu4_analysis"
require_relative "bonus_scoring"

class EvaluateCustomNation < EU4Analysis
  # from common/defines.lua
  def default_custom_idea_costs
    [0, 5, 15, 30]
  end

  def multipliers
    [
      2.0, 2.0,
      2.0, 1.8, 1.6, 1.4, 1.2, 1.0, 1.0,
      1.0,
    ]
  end

  def custom_ideas
    unless @custom_ideas
      @custom_ideas = []
      glob("common/custom_ideas/*").each do |path|
        parse(path).each do |subnode_name, subnode|
          subnode.each do |idea_name, idea|
            next if idea_name == "category"
            idea = idea.to_h
            idea.delete "default"
            idea.delete "chance"
            idea.delete "enabled"
            max_level = idea.delete("max_level") || 4
            levels = max_level.times.map do |i|
              idea.delete("level_cost_#{i+1}") || default_custom_idea_costs[i]
            end
            @custom_ideas << [idea_name, idea, levels]
          end
        end
      end
    end
    @custom_ideas
  end

  def eu4_scoring(ideas)
    puts "EU4 Scoring:"
    total = 0
    ideas.each_with_index do |(name, level), index|
      idea = custom_ideas.find{|x| x[0] == name} or raise "Cannot find idea: #{name}"
      base_cost = idea[2][level-1]
      extra_cost = base_cost * (multipliers[index] - 1).round(1)
      base_cost = base_cost.to_i if base_cost == base_cost.to_i
      extra_cost = extra_cost.to_i if extra_cost == extra_cost.to_i
      if extra_cost > 0
        puts "* #{name} #{level} - #{base_cost} + #{extra_cost}"
      else
        puts "* #{name} #{level} - #{base_cost}"
      end
      total += base_cost + extra_cost
    end
    puts "Total: #{total}"
  end

  def our_scoring(ideas)
    puts "Our Scoring:"
    total = 0
    ideas.each_with_index do |(name, level), index|
      idea = custom_ideas.find{|x| x[0] == name} or raise "Cannot find idea: #{name}"
      bonus = BonusScoring.new(idea[1])
      value = (bonus.score * level)
      eu4_cost = idea[2][level-1] * multipliers[index]
      roi = 100 * value / eu4_cost
      puts "* #{name} #{level} - #{value.round(3)} [ROI: #{roi.round(1)}]"
      total += value
    end
    puts "Total: #{total.round(3)}"
  end

  def call(*ideas)
    eu4_scoring(ideas)
    puts ""
    our_scoring(ideas)
  end
end

EvaluateCustomNation.new_from_argv.call(
  ["custom_idea_slave_raiders", 1],
  ["custom_idea_core_creation", 2],
  ["custom_global_trade_goods_size_modifier", 2],
  ["custom_idea_siege_ability", 2],
  ["custom_siege_blockade_progress", 1],
  ["custom_idea_army_tradition", 2],
  ["custom_improve_relation_modifier", 3],
  ["custom_province_warscore_cost", 2],
  ["custom_idea_colonists", 1],
  ["custom_administrative_efficiency", 2],
)
