#!/usr/bin/env ruby

require_relative "image_generation"
require_relative "../ck2/ck2_analyses"

class HolderCultureMap < ParadoxGame
  include ImageGeneration
  include Ck2Analyses

  def initialize(save_game, *roots)
    super(*roots)
    @path = save_game
    @data = ParadoxModFile.new(path: @path).parse!
  end

  def holder_cultures
    @holder_cultures ||= begin
      map = {}
      @data["provinces"].to_a.each do |prop|
        id = prop.key
        title = province_id_to_title[id]
        next unless title # wasteland or something
        holder_id = @data["title"][title]["holder"]
        map[id] = character_culture(holder_id)
      end
      map
    end
  end

  def holder_culture_map
    @holder_culture_map ||= begin
      holder_cultures.map{|i,r|
        [i, culture_colors[r]]
      }.to_h
    end
  end

  def save_path
    "output/ck2_holder_culture_#{@data["date"]}.png"
  end

  def run!
    Pathname("output").mkpath
    generate_map_image(build_color_map(holder_culture_map)).write(save_path)
  end
end

HolderCultureMap.new(*ARGV).run!
