#!/usr/bin/env ruby

require_relative "image_generation"
require_relative "../ck2/ck2_analyses"

class HolderReligionMap < ParadoxGame
  include ImageGeneration
  include Ck2Analyses

  def initialize(save_game, *roots)
    super(*roots)
    @path = save_game
    @data = ParadoxModFile.new(path: @path).parse!
  end

  def holder_religions
    @holder_religions ||= begin
      map = {}
      @data["provinces"].to_a.each do |prop|
        id = prop.key
        title = province_id_to_title[id]
        next unless title # wasteland or something
        holder_id = @data["title"][title]["holder"]
        religion = character_religion(holder_id)
        map[id] = religion
      end
      map
    end
  end

  def holder_religion_map
    @holder_religion_map ||= begin
      holder_religions.map{|i,r|
        [i, religion_colors[r]]
      }.to_h
    end
  end

  def save_path
    "output/ck2_holder_religion_#{@data["date"]}.png"
  end

  def run!
    Pathname("output").mkpath
    generate_map_image(build_color_map(holder_religion_map)).write(save_path)
  end
end

HolderReligionMap.new(*ARGV).run!
