#!/usr/bin/env ruby

require_relative "../lib/paradox_game"

class AnalyzeTrust
  def initialize(save_game)
    @data = ParadoxModFile.new(path: save_game).parse!
  end

  def call
    @data["countries"].each do |tag1, data|
      data["active_relations"].each do |tag2, relations|
        trust = relations["trust_value"] || relations["trust"] || "-"
        puts [tag1, tag2, trust].join("\t")
      end
    end
  end
end

unless ARGV.size == 1
  STDERR.puts "Usage: #{$0} save_game.eu4"
  exit 1
end

AnalyzeTrust.new(*ARGV).call
