#!/usr/bin/env ruby

require_relative "./eu4_save_analysis"

class AnalyzeTrust < EU4SaveAnalysis
  def call
    @save.countries.each do |tag1, country|
      country.node["active_relations"].each do |tag2, relations|
        trust = relations["trust_value"] || relations["trust"]
        next unless trust
        puts [tag1, tag2, trust].join("\t")
      end
    end
  end
end

if $0 == __FILE__
  AnalyzeTrust.new_from_argv.call
end
