#!/usr/bin/env ruby

require_relative "./eu4_save_analysis"

class AnalyzeDebt < EU4SaveAnalysis
  def call
    results = []

    @save.countries.each do |tag, country|
      total = country.total_loans_amount
      next if total == 0
      name = country.name || tag
      results << [total, name]
    end

    results.sort.reverse.each do |total, name|
      puts "* #{country_name(name)} - #{total}"
    end
  end
end

if $0 == __FILE__
  AnalyzeDebt.new_from_argv.call
end
