#!/usr/bin/env ruby

require_relative "./eu4_save_analysis"

class BuildingsByCountry < EU4SaveAnalysis
  def call
    country_provinces = Hash.new(0)
    country_values = Hash.new(0)

    @save.provinces.each do |id, province|
      owner = province.owner
      unless owner
        unless province.buildings.empty?
          raise "Province #{id} has buildings, but no owner!"
        end
        next
      end
      country_provinces[owner] += 1
      province.buildings.each do |building|
        country_values[owner] += building_costs[building]
      end
    end

    results = []
    country_provinces.each do |tag, provinces|
      avg = (country_values[tag].to_f / provinces).round
      results << [avg, country_name(tag), provinces]
    end
    puts results.sort.reverse.map{|row| row.join(" ") }
  end
end

if $0 == __FILE__
  BuildingsByCountry.new_from_argv.call
end
