#!/usr/bin/env ruby

require_relative "./eu4_save_analysis"

class Buildings < EU4SaveAnalysis
  def building_name(building)
    localization("building_#{building}")
  end

  def call
    totals = Hash.new(0)
    @save.provinces.each do |id, province|
      province.buildings.each do |building|
        totals[building] += 1
      end
    end
    totals.sort_by(&:last).reverse.each do |building, count|
      puts "#{building_name(building)} - #{count}"
    end
  end
end

if $0 == __FILE__
  Buildings.new_from_argv.call
end
