#!/usr/bin/env ruby

require_relative "./eu4_save_analysis"

class CulturesByDevelopment < EU4SaveAnalysis
  def call
    totals = Hash.new(0)
    @save.provinces.each do |id, province|
      next unless province.city?
      totals[province.culture] += province.development
    end
    totals.sort_by(&:last).reverse.each do |name, dev|
      puts "* #{localization(name) || "No culture"} - #{dev.round}"
    end
  end
end

if $0 == __FILE__
  CulturesByDevelopment.new_from_argv.call
end
