#!/usr/bin/env ruby

require_relative "../lib/paradox"
require_relative "eu4_save"

class CulturesByCountry < ParadoxGame
  def country_name(tag)
    @save.countries[tag]&.name || localization(tag)
  end

  def initialize(save_game, *paths)
    super(*paths)
    @save = EU4Save.new(save_game)
  end

  def culture_to_culture_group
    @culture_to_culture_group ||= begin
      map = {}
      glob("common/cultures/*.txt").each do |path|
        parse(path).each do |group_name, group|
          group.each do |culture_name, culture|
            next unless culture.is_a?(PropertyList)
            map[culture_name] = group_name
          end
        end
      end
      map
    end
  end

  def cultures_by_country
    @cultures_by_country ||= begin
      totals = {}
      @save.provinces.each do |id, province|
        next unless province.city?
        next unless province.owner
        if province.development == 0
          # warn "Zero development province #{province.id} #{province.name}"
          next
        end
        totals[province.owner] ||= Hash.new(0)
        totals[province.owner][province.culture] += province.development
      end
      totals
    end
  end

  def same_culture_group?(a, b)
    culture_to_culture_group[a] == culture_to_culture_group[b]
  end

  def country_sizes
    @country_sizes ||= begin
      totals = Hash.new(0)
      @save.provinces.each do |id, province|
        next unless province.city?
        if province.development == 0
          # warn "Zero development province #{province.id} #{province.name}"
          next
        end
        totals[province.owner] += province.development
      end
      totals
    end
  end

  def culture_status(tag, culture)
    country = @save.countries[tag]
    return "primary" if culture == country.primary_culture
    return "accepted" if country.accepted_cultures.include?(culture)
    if same_culture_group?(culture, country.primary_culture)
      if country.government_rank == 3
        "union"
      else
        "related"
      end
    else
      nil
    end
  end

  def call
    country_sizes.sort_by(&:last).reverse.each do |tag, size|
      puts "#{country_name(tag)}:"
      cultures = cultures_by_country[tag]
      cultures.sort_by(&:last).reverse.each do |culture_name, dev|
        status =  culture_status(tag, culture_name)
        status = " [#{status}]" if status
        puts "* #{localization(culture_name)}#{status} - #{dev.round}"
      end
      puts ""
    end
  end
end

unless ARGV.size >= 2
  STDERR.puts "Usage: #{$0} <save.eu4> <root> [<mod1> <mod2> ... ] # non-compressed save only"
  exit 1
end

CulturesByCountry.new(*ARGV).call
