#!/usr/bin/env ruby

require_relative "./eu4_save_analysis"

class HREReligions < EU4SaveAnalysis
  def capital_in_hre?(tag)
    capital = @data["countries"][tag]["capital"]
    return false if capital == nil or capital == 0
    !!@data["provinces"][-capital]["hre"]
  end

  def country_on_map?(tag)
    !!@data["countries"][tag]["num_of_cities"]
  end

  def call
    hre_members_religions = []
    @save.countries.each do |tag, country|
      next unless country.on_map? and country.hre?
      hre_members_religions << [country.religion, country_name(tag)]
    end
    hre_members_religions.sort.each do |religion, country_name|
      puts "#{religion}: #{country_name}"
    end
  end
end

if $0 == __FILE__
  HREReligions.new_from_argv.call
end
