#!/usr/bin/env ruby

require "set"
require_relative "../lib/paradox"

class ReleasableHRECountries < ParadoxGame
  def initialize(save_game, *paths)
    super(*paths)
    @path = save_game
    @data = ParadoxModFile.new(path: @path).parse!
  end

  def foreign_cores
    @foreign_cores ||= begin
      map = {}
      @data["provinces"].each do |id, province|
        # Old and new saves use different format
        cores = province.find_all("core") + (province["cores"] || [])
        owner = province["owner"]
        next unless province["hre"]
        cores.each do |core|
          next if core == owner
          map[core] ||= Hash.new(0)
          map[core][owner] += 1
        end
      end
      map
    end
  end

  def country_size(tag)
    @data["countries"][tag]["num_of_cities"] || 0
  end

  def call
    foreign_cores.each do |country, foreigners|
      next if country_size(country) > 0
      with_counts = foreigners.map{|tag,count| "#{localization(tag)} (#{count})"}.join(", ")
      puts "#{localization(country)}: #{ with_counts }"
    end
  end
end

unless ARGV.size >= 2
  STDERR.puts "Usage: #{$0} <save.eu4> <root> [<mod1> <mod2> ... ] # non-compressed save only"
  exit 1
end

ReleasableHRECountries.new(*ARGV).call
