#!/usr/bin/env ruby

require_relative "../lib/paradox_game"

class WorldConquestProgress < ParadoxGame
  def initialize(save_game, *paths)
    @data = ParadoxModFile.new(path: save_game).parse!
    super(*paths)
  end

  def provinces
    unless @provinces
      @provinces = {}
      @data["provinces"].each do |id, province|
        dev = (province["base_tax"] || 0) +
              (province["base_production"] || 0) +
              (province["base_manpower"] || 0)
        next if dev == 0
        # Fractional dev used to be the case for colonies, they removed it by now right?
        dev = dev.to_i if dev == dev.to_i
        owner = province["owner"]
        @provinces[-id] = {dev: dev, owner: owner}
      end
    end
    @provinces
  end

  def country_development
    unless @country_development
      @country_development = {}
      provinces.each do |id, province|
        owner = province[:owner]
        @country_development[owner] ||= 0
        @country_development[owner] += province[:dev]
      end
    end
    @country_development
  end

  def player_tag
    # New compressed saves stopped recording this in player tag
    @player_tag ||= @data["player"] || @data["countries"].keys.find{|tag| @data["countries"][tag]["human"]}
  end

  def subjects
    unless @subjects
      @subjects = {}
      @data["diplomacy"].each do |type, relation|
        next unless relation["subject_type"]
        subject_type = relation["subject_type"]
        overlord = relation["first"]
        subject = relation["second"]
        if @subjects[subject]
          relation1 = "#{subject_type} of #{overlord}"
          overlord2, subject_type2 = @subjects[subject]
          relation2 = "#{subject_type2} of #{overlord2}"
          warn "#{subject} is #{relation1} but it's #{relation2} already"
          next
        end
        @subjects[subject] = [overlord, subject_type]
      end
    end
    @subjects
  end

  def development_by_type
    @development_by_type ||= begin
      map = Hash.new(0)
      country_development.each do |tag, dev|
        if tag == player_tag
          map[:own] += dev
        elsif tag == nil
          map[:uncolonized] += dev
        elsif subjects[tag] and subjects[tag][0] == player_tag
          map[subjects[tag][1]] += dev
        else
          map[:foreigners] += dev
        end
      end
      map
    end
  end

  def development_by_independent_country
    @development_by_independent_country ||= begin
      map = Hash.new(0)
      country_development.each do |tag, dev|
        if tag == nil
          # skip
        elsif subjects[tag]
          map[subjects[tag][0]] += dev
        else
          map[tag] += dev
        end
      end
      map
    end
  end

  def call
    development_by_type.each do |type, dev|
      puts "#{type}: #{dev}"
    end
    puts ""
    development_by_independent_country
      .sort_by{|tag,dev| [-dev, tag]}
      .each do |tag, dev|
      puts "#{localization(tag)}: #{dev}"
    end
  end
end

unless ARGV.size >= 2
  STDERR.puts "Usage: #{$0} <save.eu4> <root> [<mod1> <mod2> ... ] # non-compressed save only"
  exit 1
end

WorldConquestProgress.new(*ARGV).call
