#!/usr/bin/env ruby

require_relative "./eu4_save_analysis"

class WorldConquestProgress < EU4SaveAnalysis
  def provinces
    unless @provinces
      @provinces = {}
      @save.provinces.each do |id, province|
        dev = province.development
        next if dev == 0
        # Fractional dev used to be the case for colonies, they removed it by now right?
        dev = dev.to_i if dev == dev.to_i
        owner = province.owner
        @provinces[-id] = {dev: dev, owner: owner}
      end
    end
    @provinces
  end

  def country_development
    unless @country_development
      @country_development = {}
      provinces.each do |id, province|
        owner = province[:owner]
        @country_development[owner] ||= 0
        @country_development[owner] += province[:dev]
      end
    end
    @country_development
  end

  def player_tag
    @save.player_tag
  end

  def subjects
    @save.subjects
  end

  def development_by_type
    @development_by_type ||= begin
      map = Hash.new(0)
      country_development.each do |tag, dev|
        if tag == player_tag
          map[:own] += dev
        elsif tag == nil
          map[:uncolonized] += dev
        elsif subjects[tag] and subjects[tag][0] == player_tag
          map[subjects[tag][1]] += dev
        else
          map[:foreigners] += dev
        end
      end
      map
    end
  end

  def development_by_independent_country
    @development_by_independent_country ||= begin
      map = Hash.new(0)
      country_development.each do |tag, dev|
        if tag == nil
          # skip
        elsif subjects[tag]
          map[subjects[tag][0]] += dev
        else
          map[tag] += dev
        end
      end
      map
    end
  end

  def call
    development_by_type.each do |type, dev|
      puts "#{type}: #{dev}"
    end
    puts ""
    development_by_independent_country
      .sort_by{|tag,dev| [-dev, tag]}
      .each do |tag, dev|
      puts "#{country_name(tag)}: #{dev}"
    end
  end
end

if $0 == __FILE__
  WorldConquestProgress.new_from_argv.call
end
