NDefines = {

NCharacters = {
	MAX_STATS = 6,
	RULER_STATS_DIVIDER = 3.0,
	YOUNG_RULER_MODIFIER = 10.0,
	YOUNG_RULER_AGE = 16.0,
	HEIR_STATS_DIVIDER = 3.0,
	YOUNG_HEIR_MODIFIER = 10.0,
	YOUNG_HEIR_AGE = 16.0,
	TREASURY_DIVIDER = 10,
	PRESTIGE_DIVIDER = 50,
},

NEmpire = {
	HRE_TITLE = "e_dyn_2439406",
	UNITED_CROWN_LAW_STAGE = 4,
	MAX_ELECTORS = 7,
},

NNation = {
	PERSERVE_HUMAN_VASSALS = 1,
	INDEPENDENT_VASSALS_CROWN_LAW_STAGE = 0,
	MAX_VASSALS = 4,
},

NMisc = {
	START_DATE_YEAR = 1444,
	START_DATE_MONTH = 11,
	START_DATE_DAY = 11,
	EU4_VERSION = "1.28",
},

NTechGroups = {
	EASTERN_ABOVE_AVERAGE_BOUND = 6,
	EASTERN_BELOW_AVERAGE_BOUND = -0,
	KEY_PROVINCE_BOOST = 1,
	ORGANIZED_RELIGION_BOOST = 6,
},

}
