#!/usr/bin/env ruby

require_relative "../lib/paradox"
require_relative "trade_graph"

class ExportTradeGraph < ParadoxGame
  def call
    tg = TradeGraph.new(parse("common/tradenodes/00_tradenodes.txt"))
    tg.edges.each do |from, to|
      puts [from, to].join(" ")
    end
  end
end

ExportTradeGraph.new(*ARGV).call
