#!/usr/bin/env ruby

require_relative "../lib/paradox"
require_relative "trade_graph"

class ExportTradeGraph < ParadoxGame
  def initialize(trade_graph_file, *args)
    super(*args)
    @trade_graph = TradeGraph.new(parse("common/tradenodes/00_tradenodes.txt"))
    @updated_edge_list = open(trade_graph_file, &:readlines).map{|line| line.chomp.split}
  end

  def call
    updated_node = @trade_graph.rewrite(@updated_edge_list)
    puts ParadoxModFileSerializer.serialize(updated_node)
  end
end

ExportTradeGraph.new(*ARGV).call
