#!/usr/bin/env ruby

require "rgl/adjacency"
require "rgl/connected_components"

trade_graph_data = ARGF.readlines.map{|line| line.chomp.split}
trade_graph = RGL::DirectedAdjacencyGraph[*trade_graph_data.flatten]

inv_comp_map = {}
trade_graph.strongly_connected_components.comp_map.each do |v, n|
  (inv_comp_map[n] ||= []) << v
end
loops = inv_comp_map.values.delete_if { |scc| scc.size == 1 }

if loops.empty?
  puts "Everything works!"
else
  puts "There are loops:"
  puts loops.map(&:inspect)
end
