#!/usr/bin/env ruby

require_relative "simple_terrain_map_mod"

class BuildSimpleTerrainMapMod < ParadoxModBuilder
  include SimpleTerrainMapMod
  def initialize
    super(
      ParadoxGame.new(
        "source/hoi4-1.3.3",
        "source/KR-0.4.3",
      ),
      "output/simple_terrain_map_mode_kr"
    )
  end

  def mod_name
    "simple_terrain_map_mode_kr"
  end

  def build_mod_files!
    apply_simple_terrain_map_mod!
    create_mod_descriptor!(
      name: "Simple Terrain Map Mode KR",
      path: "mod/simple_terrain_map_mode_kr",
      supported_version: "1.3.*",
    )
  end
end

BuildSimpleTerrainMapMod.new.build!
