#!/usr/bin/env ruby

require_relative "simple_terrain_map_mod"

class BuildSimpleTerrainMapMod < ParadoxModBuilder
  include SimpleTerrainMapMod
  def initialize
    super(
      ParadoxGame.new(
        "source/hoi4-1.5.4",
      ),
      "output/#{mod_name}"
    )
  end

  def mod_name
    "a_simple_terrain_map_mode"
  end

  def build_mod_files!
    apply_simple_terrain_map_mod!
    create_mod_descriptor!(
      name: "A Simple Terrain Map Mode",
      path: "mod/#{mod_name}",
      supported_version: "1.5.*",
      picture: "a_simple_terrain_map_mode.png",
    )
  end
end

BuildSimpleTerrainMapMod.new.build!
