#!/usr/bin/env ruby

require "pp"
require "pathname"
require_relative "../lib/paradox"
require_relative "bonus_scoring"

class AnalyzePolicies < ParadoxGame
  def each_policy
    glob("common/policies/*").each do |path|
      parse(path).each do |policy|
        yield(policy)
      end
    end
  end

  def analyze_policies!
    each_policy do |name, policy|
      policy = policy.to_h
      point_type = policy["monarch_power"].downcase
      policy.delete("potential")
      policy.delete("monarch_power")
      policy.delete("ai_will_do")
      requirements = policy.delete("allow").to_h["full_idea_group"].map{|i| i.sub("_ideas", "")}

      bonuses = BonusScoring.new
      bonuses.send("monthly_#{point_type}_points", -1.0)
      policy.each do |k,v|
        bonuses.send(k,v)
      end
      puts [bonuses.score, name, *requirements, point_type, policy.inspect].join("\ ")
    end
  end
end

AnalyzePolicies.new(*ARGV).analyze_policies!
