require "pathname"

# These do not belong in any modpack (total conversions etc.)
# or conflict with other mods
excluded_mods = [
  "mnr ck2plus", # ck2+ submod
  "modern_flags", # submod for modern_times
  "modern_times", # total conversion
  "no_artifact_losing", # already included
  "no_localized_ranks", # already included
  "no_satan_masks_red_cloth", # animeportraits
  "paganwomengetconsorts", # too many conflicts
  "unlimited focus", # already included
  "world of ideologies", # modern times stuff
]

desc "Unpack Steam and mods"
task "mods:unpack:steam" do
  Pathname("mods_unpacked").mkpath
  Pathname("steam_mods").children.each do |path|
    if path.extname == ".mod"
      bn = path.basename(".mod").basename(".mod").to_s
      next if excluded_mods.include?(bn)
      FileUtils.cp path, Pathname("mods_unpacked") + path.basename
    elsif path.extname == ".zip"
      bn = path.basename(".zip").to_s
      next if excluded_mods.include?(bn)
      dest_path = Pathname("mods_unpacked") + path.basename(".zip")
      dest_path.mkpath
      Dir.chdir(dest_path) do
        sh "7za", "x", "-aou", "../../#{path}"
        # Steam weird stuff, two descriptors in same zip
        ["thumb.jpg", "descriptor.mod", "descriptor_1.mod", "changelog.txt"].each do |bad_file|
          if File.exist?(bad_file)
            FileUtils.rm bad_file
          end
        end
      end
    end
  end
end

task "mods:unpack" => ["cleanup", "mods:unpack:steam", "mods:unpack:gavelkind"]

desc "Unpack mods from gavelkind"
task "mods:gavelkind:unpack" do
  # ...
end

desc "Get mods from gavelkind"
task "mods:gavelkind:fetch" do
  Pathname("gavelkind_mods").mkpath
  Dir.chdir("gavelkind_mods") do
    sh "git clone https://github.com/gavelkind/transfer_empty_province"
    sh "git clone https://github.com/gavelkind/heir_traits"
    sh "git clone https://github.com/gavelkind/vassal_culture_alerts"
    sh "git clone https://github.com/gavelkind/pact_traits"
    # https://github.com/gavelkind/invitation_traits # in base game now?
    # https://github.com/gavelkind/challenge_traits # don't want
    sh "git clone https://github.com/gavelkind/title_info"
    # https://github.com/gavelkind/fitna_fracture # using Steam version
    sh "git clone https://github.com/gavelkind/show_council"
    sh "git clone https://github.com/gavelkind/notify_on_adulthood"
    # https://github.com/gavelkind/elective_leagues # don't want
  end
end

desc "Show mod conflicts"
task "mods:conflicts" do
  sh "../bin/check_mod_compatibility mods_unpacked"
end

desc "Cleanup"
task "cleanup" do
  sh "trash", "mods_unpacked"
end
