ModernTimesDatabase::CULTURES = {
  "d_ascalon"      => "ashkenazi",
  "d_crimea"       => "russian",
  "d_sevilla"      => "castillan",
  "d_granada"      => "castillan",
  "c_algeciras"    => "english",
  "d_nyitra"       => "bohemian",
  "c_pressburg"    => "bohemian",
  "d_carinthia"    => "croatian",
  "c_steiermark"   => "croatian",
  "d_armenia"      => "armenian",
  "c_famagusta"    => "turkish",
  "c_byzantion"    => "turkish",
  "c_trent"        => "german",
  "c_dublin"       => "irish",
  "d_samos"        => "greek",
  "d_adrianopolis" => "greek",
  "d_moldau"       => "romanian",
  "d_kiev"         => "russian",
  "d_pereyaslavl"  => "russian",
  "d_silesia"      => "polish",
  # Until we get Ukrainian culture
  "d_galich"       => "polish",
  "d_volhynia"     => "polish",
  # Just remove mongols, all of these horde cultures feel temporary
  "k_cuman"        => "cuman",
  "k_turkestan"    => "cuman",
  "k_alania"       => "alan",
  "c_khopyor"      => "cuman",
  "c_chortitza"    => "bolghar",
  "c_dashhowuz"    => "karluk",
  "c_ural"         => "cuman",
  "d_samarkand"    => "karluk",
  "c_bashkirs"     => :keep,
  "c_mangyshlak"   => :keep,
}
