ModernTimesDatabase::RELIGIONS = {
  "k_england"     => "protestant",
  "d_mecklemburg" => "protestant",
  "d_crimea"      => "orthodox",
  "d_armenia"     => "orthodox",
  "k_persia"      => "shiite",
  "d_basra"       => "shiite",
  "d_tigris"      => "shiite",
  "d_baghdad"     => "shiite",
  "d_kermanshah"  => "shiite",
  "d_tripoli"     => "shiite",
  "d_kola"        => :keep,
  "d_karelia"     => :keep,
  "e_scandinavia" => "protestant",
  "d_brandenburg" => "protestant",
  "d_brunswick"   => "protestant",
  "d_courland"    => "protestant",
  "d_ascalon"     => "jewish",
  "d_holland"     => "reformed",
  "d_gelre"       => "reformed",
  "d_upper_burgundy" => "reformed",
  "k_scotland"    => "reformed",
  "d_alexandria"  => "sunni",
  "d_cairo"       => "sunni",
  "d_damietta"    => "sunni",
  "d_sevilla"     => "catholic",
  "d_granada"     => "catholic",

  # UPDATES:
  # "c_algeciras"   => "protestant",
}
