desc "Run tests"
task "test" do
  sh "rspec"
end

desc "Run importer - Vanilla"
task "import" do
  sh "rescue ./bin/import_data vanilla ~/hoi4"
end

desc "Run importer - Millennium Dawn"
task "import:md" do
  sh "rescue ./bin/import_data millennium_dawn ~/px/source/MD-1.9.1"
end

desc "Run importer - Kaiserreich"
task "import:kr" do
  sh "rescue ./bin/import_data kaiserreich ~/hoi4 ~/px/source/KR-1.9.1"
end

desc "Run importer - Road to 56"
task "import:r56" do
  sh "rescue ./bin/import_data road_to_56 ~/hoi4 ~/px/source/R56-1.9.3"
end

desc "Run importers - all working"
task "import:all" => ["import", "import:kr", "import:r56"]
